xJonathanLEI/starknet-rs

starknet-core/src/types/contract_code.rs
=> fix: add missing `stateMutability` field to `AbiFunctionEntry`

Cargo.lock, starknet-contract/Cargo.toml, starknet-contract/src/factory.rs, starknet-contract/src/lib.rs, starknet-contract/tests/contract_deployment.rs, starknet-core/src/types/contract_code.rs, starknet-core/src/types/starknet_error.rs, starknet-core/src/types/transaction_request.rs
Resolves task 3 of #6:
> add type for deploying artifact through `starknet_providers::Provider`
=> feat: implement `ContractFactory` for contract deployment

starknet-core/src/types/field_element/mod.rs, starknet-core/src/types/field_element/unsigned.rs, starknet-core/src/types/mod.rs
Resolves task 1 of #13:
> add `UnsignedFieldElement` type as wrapper around `U256`
=> feat: add `UnsignedFieldElement` type

README.md
Resolves task 3 of #50:
> add example to `README` and mark feature as done
Note that this PR should be merged _after_ #51. Otherwise it doesn't make sense :))
=> docs: add example for using `Account` to `README`

starknet-contract/src/lib.rs
This PR makes `starknet_contract::artifadt` public.
=> misc: make `starknet_contract::artifact` public

starknet-core/src/serde/unsigned_field_element.rs
An empty string `""` that's being deserialized with `hex_option` to a field of type `Option<UnsignedFieldElement>` currently deserializes to `Some(UnsignedFieldElement { inner: 0 })` instead of `None`. This PR fixes it.
I don't have an example of the API sending an empty string in e.g. a `block_hash`, I just found out when I was writing a test case by hand.
I wasn't sure how to unit test a custom deserializer, found [serde-test](https://docs.serde.rs/serde_test/) but I don't have a clue how to use it in this case. Then I found [this on SA](https://stackoverflow.com/questions/56985101/how-to-unit-test-a-deserialization-function-used-in-serdedeserialize-with) and adapted it, works pretty well IMO.
The matching code in hex_option's deserialize is kinda ugly though. Is there a prettier way …
=> fix: deser or empty string to Option<UnsignedFieldElement>

starknet-core/Cargo.toml, starknet-core/src/types/contract_code.rs
=> fix: allow arbitrary precision in contract artifacts

README.md
=> doc: add JSON-RPC client to feature roadmap

starknet-accounts/src/single_owner.rs, starknet-core/src/types/call_contract.rs, starknet-core/src/types/mod.rs, starknet-providers/src/provider.rs, starknet-providers/src/sequencer_gateway.rs
=> refactor: use InvokeFunction from transaction_request.rs

starknet-accounts/src/single_owner.rs, starknet-core/src/types/transaction.rs, starknet-core/src/types/transaction_request.rs, starknet-ff/src/lib.rs
Resolves task 3 of #85:
> add support for paying transaction fees
=> feat: support paying transaction fees

README.md
Adding a line about the Goerli faucet and TX fees to the example in README
=> doc: mention L2 faucet to pay for TX fees

starknet-accounts/src/single_owner.rs
=> feat: add fee estimate buffer

README.md
=> doc: add badge for supported StarkNet version

Cargo.lock, Cargo.toml, README.md, examples/deploy_contract.rs, examples/get_block.rs, examples/mint_tokens.rs
=> doc: move examples out of README

README.md
=> doc: fix broken link on README

starknet-accounts/src/account.rs, starknet-accounts/src/lib.rs, starknet-accounts/src/single_owner.rs, starknet-accounts/tests/single_owner_account.rs
=> feat: add `estimate_fee` to `Account` trait

starknet-core/src/utils.rs, starknet-ff/src/lib.rs
This PR:
- implements the remainder operator for `FieldElement`; and
- adds the `get_storage_var_address` utility function for calculating storage variable addresses.
=> feat: add `get_storage_var_address` util function

starknet-core/src/utils.rs
This PR adds a new util function `parse_cairo_short_string` for parsing Cairo short strings.
=> feat: implement Cairo short string parsing

Cargo.lock, starknet-providers/Cargo.toml
Turns out I forgot to remove dependency on OpenSSL with `reqwest`. This PR fixes that.
=> chore: remove OpenSSL dependency

README.md
Resolves task 4 of #129:
> declare v0.9.0 support on README
=> docs: update supported StarkNet version

starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/jsonrpc/transports/http.rs, starknet-providers/src/jsonrpc/transports/mod.rs
Partially implements #77.
This PR adds error handling to the JSON-RPC client.
=> feat(jsonrpc): implement error handling

starknet-ff/src/lib.rs
This PR adds a new method `floor_div` to `FieldElement`.
I'm adding this method instead of implementing `Div` so that we can support both floor division and felt division at the same time, without footgun.
=> feat: implement floor division for FieldElement

starknet-ff/src/lib.rs
This PR implements `std::str::FromStr` for `FieldElement`.
=> feat: implement FromStr for FieldElement

starknet-ff/src/lib.rs
=> feat: implement `Default` for `FieldElement`

starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/jsonrpc/models/mod.rs, starknet-providers/tests/jsonrpc.rs
=> feat(jsonrpc): implement new methods

starknet-providers/src/lib.rs
=> feat: expose sequencer provider error type

starknet-core/src/utils.rs
=> feat: remove name from `NonAsciiNameError`

starknet-accounts/src/single_owner.rs, starknet-accounts/tests/single_owner_account.rs, starknet-core/src/types/fee.rs
=> fix(FeeEstimate): rename "amount" to "overall_fee"

README.md
=> docs: bump supported StarkNet version to 0.10.0

starknet-core/src/utils.rs
This PR implements local contract address calculation. It's necessary for an actually usefaul `DeployAccount` implementation (#224) as users would need to fund the addresses first.
=> feat: calculate contract address

README.md
Closes #250.
This PR simply bumps the numbers on README.
=> docs: bump supported versions in README

starknet-providers/src/sequencer_gateway.rs
=> feat: rate limited error on sequencer provider

starknet-providers/src/jsonrpc/models/codegen.rs, starknet-providers/src/jsonrpc/models/mod.rs
=> feat(jsonrpc): derive eq traits for `BlockId`

Cargo.lock, README.md, examples/deploy_contract.rs, starknet-contract/Cargo.toml, starknet-contract/src/factory.rs, starknet-contract/src/lib.rs, starknet-contract/tests/contract_deployment.rs
Implements the first half of #232.
This PR adds support for [UDC](https://community.starknet.io/t/universal-deployer-contract-proposal) for contract deployment.
=> feat: contract deployment via UDC

tests/macros.rs
Forgot to add test case in #283.
=> test: add test case for `short_string!()`

examples/get_block.rs, examples/jsonrpc.rs, examples/starknet-wasm/src/lib.rs, starknet-contract/tests/contract_deployment.rs, starknet-core/src/serde/byte_array.rs, starknet-core/src/serde/num_hex.rs, starknet-core/src/serde/unsigned_field_element.rs, starknet-core/src/types/contract_artifact.rs, starknet-core/src/types/contract_code.rs, starknet-crypto-codegen/src/lib.rs, starknet-ff/src/lib.rs, starknet-providers/src/jsonrpc/models/serde_impls.rs, starknet-providers/src/sequencer_gateway.rs
=> chore: fix new clippy warnings from Rust 1.67.0

Cargo.lock, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto/Cargo.toml, starknet-ff/Cargo.toml, starknet-providers/Cargo.toml
Just a simple dependency bump.
=> chore: bump `serde` to 1.0.152

BENCHMARK.md, examples/starknet-wasm/README.md, starknet-crypto/README.md
=> Fix: typos

starknet-core/src/crypto.rs, starknet-crypto/src/ecdsa.rs, starknet-crypto/src/error.rs, starknet-crypto/src/lib.rs, starknet-curve/src/ec_point.rs, starknet-signers/src/key_pair.rs
=> feat: elliptic curve recovery

starknet-core/src/types/contract/mod.rs
This PR implements (again) the compiled casm class hash calculation.
Great thanks to @ArielElp for taking the feedback and changing the algo! It's much much much cleaner and easier to implement now.
=> feat: compiled class hash calculation

starknet-providers/tests/jsonrpc.rs
=> test: disable failing jsonrpc tests

starknet-providers/src/jsonrpc/provider.rs, starknet-providers/src/provider.rs, starknet-providers/src/sequencer_gateway.rs
Resolves task 6 of #313:
> add support for new sequencer gateway methods
=> feat: new method added in v0.11.0

README.md
=> docs: bump supported Starknet version to 0.11.0

Cargo.toml, README.md, src/lib.rs
=> docs: comply with the new trademark policy

Cargo.lock, examples/starknet-wasm/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto/Cargo.toml, starknet-signers/Cargo.toml
The only change was a perf improvement in #355. Bumping patch version.
=> release: bump starknet-crypto to 0.4.3

Cargo.lock, examples/starknet-wasm/Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-core/src/serde/byte_array.rs, starknet-crypto-codegen/Cargo.toml, starknet-crypto/Cargo.toml, starknet-ff/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
=> chore: bump dependencies

scripts/build_bench_wasm.sh, scripts/run_bench_wasm.sh, starknet-core/README.md, starknet-crypto/README.md
Updates benchmark results again to reflect the significant improvements introduced in #368.
=> docs: update benchmark results

starknet-providers/src/jsonrpc/models/codegen.rs, starknet-providers/src/jsonrpc/models/mod.rs
Regenerates jsonrpc model code with the latest `starknet-jsonrpc-codegen` commit.
=> feat(jsonrpc): regenerate model types

starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/jsonrpc/models/codegen.rs, starknet-providers/src/jsonrpc/models/mod.rs, starknet-providers/src/jsonrpc/provider.rs, starknet-providers/tests/jsonrpc.rs
For renaming `ErrorCode` to `StarknetError`.
=> feat: regenerate jsonrpc model code

Cargo.lock, starknet-signers/Cargo.toml, starknet-signers/src/signer.rs
This helps avoid some unnecessary clones.
=> feat: auto smart pointer impls for `Signer`

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
This is to release an important patch in #404.
=> release: bump starknet-core to 0.3.1

starknet-ff/src/lib.rs
Also adds conversion test cases.
=> feat(ff): u128 conversion

Cargo.lock, examples/starknet-wasm/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto-codegen/Cargo.toml, starknet-crypto/Cargo.toml, starknet-curve/Cargo.toml, starknet-ff/Cargo.toml
=> release: bump starknet-ff to 0.3.4

starknet-core/src/utils.rs
Based on the [UDC implementation](https://github.com/OpenZeppelin/cairo-contracts/blob/70cbd05ed24ccd147f24b18c638dbd6e7fea88bb/src/openzeppelin/utils/presets/UniversalDeployer.cairo).
=> feat: udc deployed address calculation

starknet-core/src/utils.rs
=> fix: typo in udc settings field

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
=> release: bump starknet-core to 0.3.2

.github/workflows/build.yml
Gotta make sure all combinations build.
=> ci: all feature combinations should build

starknet-core/src/types/codegen.rs, starknet-core/src/types/mod.rs, starknet-core/src/types/serde_impls.rs, starknet-providers/src/sequencer/models/conversions.rs
=> feat: support DECLARE tx v0

starknet-providers/src/sequencer/models/conversions.rs
In the upcoming Starknet version 0.12.0, the `PENDING` transaction status will be removed. However, transactions can still live in a pending block, and hence not have a block hash. Per JSON-RPC specs transactions that do not have a block hash shall still be considered `PENDING`.
Technically we should wait for `0.12.0` to be officially released first before merging this, but this behavior is very unlikely to be changed, so we might as well just merge it first.
=> feat: interpret tx as pending conditionally

Cargo.lock, starknet-core/Cargo.toml, starknet-core/src/crypto.rs, starknet-core/src/types/codegen.rs, starknet-core/src/types/contract/mod.rs, starknet-core/src/utils.rs
Manually implement the error traits instead.
=> refactor(core): remove dependency on `thiserror`

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
Madara needs the changes from #439.
Bumping the minor version as this release contains breaking changes.
=> release: bump starknet-core to 0.5.0

starknet-accounts/tests/single_owner_account.rs, starknet-contract/tests/contract_deployment.rs, starknet-providers/tests/jsonrpc.rs
=> test: make hardcoded RPC address configurable

starknet-providers/tests/jsonrpc.rs
The pathfinder bugs have been fixed in version 0.7.2.
=> test: re-enable ignored tests

Cargo.lock, Cargo.toml, examples/starknet-wasm/Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto-codegen/Cargo.toml, starknet-crypto/Cargo.toml, starknet-curve/Cargo.toml, starknet-ff/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
To make #491 and #492 available.
=> release: bump starknet-ff and starknet-core

.github/workflows/artifacts.yml, starknet-core/test-data/contracts/cairo0/generate_artifacts.sh, starknet-core/test-data/contracts/cairo1/generate_artifacts.sh, starknet-core/test-data/contracts/cairo2/generate_artifacts.sh
Adds a new workflow that makes sure contract artifact files are up to date.
=> ci: check contract artifact staleness

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml
=> release: bump starknet-accounts to 0.6.1

Cargo.lock, Cargo.toml, examples/starknet-wasm/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto-codegen/Cargo.toml, starknet-crypto/Cargo.toml, starknet-curve/Cargo.toml, starknet-ff/Cargo.toml
=> release: bump starknet-ff to 0.3.6

starknet-providers/src/sequencer/mod.rs
Allows setting additional custom headers to sequencer requests. An example use case for this is using a rate limit bypassing API key.
=> feat(sequencer): custom request headers

starknet-providers/src/jsonrpc/transports/http.rs
Same as #578 but for the JSON-RPC transport.
=> feat(jsonrpc): custom request headers

Cargo.lock, starknet-core/Cargo.toml, starknet-core/src/types/mod.rs, starknet-core/src/types/u256.rs
The `u256` Cairo type equivalent for `starknet-rs`.
=> feat: U256 type

starknet-core/src/types/receipt_block.rs
- the macro `#[serde_as]` must be declared before `#[derive(...)]`
- the serialization of the block_hash as a `FieldElement` was done in base 10 but this is correct with Felt
=> fix: serialization ReceiptBlock

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
Mainly to make #612 available.
=> release: bump starknet-core to 0.11.1

Cargo.lock, Cargo.toml, examples/starknet-wasm/Cargo.toml, starknet-accounts/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto/Cargo.toml, starknet-signers/Cargo.toml
=> release: bump starknet-crypto to 0.7.1

starknet-signers/src/ledger.rs
Forgot to expose the 2 methods in #621.
=> fix: `LedgerStarknetApp` method privacy

starknet-providers/src/sequencer/mod.rs
Fixes a new nightly hint warning.
=> chore: make clippy happy again

starknet-accounts/src/single_owner.rs, starknet-crypto/README.md, starknet-crypto/src/ecdsa.rs, starknet-crypto/src/error.rs, starknet-crypto/src/lib.rs, starknet-crypto/src/pedersen_hash.rs, starknet-crypto/src/poseidon_hash.rs, starknet-crypto/src/rfc6979.rs
=> docs: add docs for `starknet-crypto`

starknet-accounts/tests/single_owner_account.rs
Temporarily taking down the Juno node for running `starknet-rs` tests.
=> test: run tests against pathfinder

starknet-providers/src/any.rs, starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/jsonrpc/transports/http.rs, starknet-providers/src/jsonrpc/transports/mod.rs, starknet-providers/src/lib.rs, starknet-providers/src/provider.rs
=> docs: add docs for `starknet-providers`

Cargo.lock, Cargo.toml, examples/starknet-wasm/Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-crypto/Cargo.toml, starknet-curve/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
=> release: bump starknet to 0.12.0 (and deps)

Cargo.lock, starknet-core/Cargo.toml, starknet-crypto/Cargo.toml, starknet-curve/Cargo.toml
=> bump `starknet-types-core` to `0.1.5`

starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/jsonrpc/transports/http.rs
Derive `Clone` for `HttpTransport` and `JsonRpcClient`.
=> dev: derive clone

starknet-accounts/src/account/declaration.rs, starknet-accounts/src/account/execution.rs, starknet-accounts/src/factory/mod.rs, starknet-contract/src/factory.rs
More lifetimes that can be elided.
=> chore: make nightly clippy happy

starknet-signers/src/ledger.rs
Current version of the SDK generate incorrect signatures when using Ledger apps of newer versions. This PR fixes it while remaining compatible with older versions by adding an app version query.
=> feat: hash encoding for Ledger app v2.0.0+

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-signers/Cargo.toml
=> release: bump starknet-signers to 0.10.2

examples/starknet-cxx/CMakeLists.txt, starknet-providers/tests/jsonrpc.rs
Context: https://github.com/corrosion-rs/corrosion/pull/591.
=> chore: bump corrosion for `FindRust` fix

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
=> release: bump starknet-core to 0.12.2

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml
Switches to use JSON-RPC spec v0.8.0.
=> release: bump starknet to 0.14.0 (and deps)

Cargo.lock, Cargo.toml, README.md, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-providers/Cargo.toml, starknet-tokio-tungstenite/Cargo.toml
To make #729 available. Adds a feature `worker` to the crate.
=> release: bump starknet to 0.15.1

examples/snip_12_json.rs, starknet-core/src/types/typed_data/domain.rs, starknet-core/src/types/typed_data/mod.rs, starknet-core/src/types/typed_data/revision.rs, starknet-core/src/types/typed_data/shortstring.rs, starknet-core/src/types/typed_data/type_definition.rs, starknet-core/src/types/typed_data/type_reference.rs, starknet-core/src/types/typed_data/types.rs, starknet-core/src/types/typed_data/value.rs
Implements `Serialize` on `TypedData`.
=> feat: SNIP-12 typed data serialization

Cargo.lock, Cargo.toml, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml, starknet-tokio-tungstenite/Cargo.toml
=> release: bump starknet to 0.16.0 (and deps)

README.md, examples/batch.rs, examples/declare_cairo1_contract.rs, examples/deploy_account_with_ledger.rs, examples/deploy_argent_account.rs, examples/deploy_contract.rs, examples/erc20_balance.rs, examples/get_block.rs, examples/jsonrpc.rs, examples/mint_tokens.rs, examples/transfer_with_ledger.rs, examples/websocket.rs, starknet-accounts/src/single_owner.rs, starknet-accounts/tests/ledger.rs, starknet-accounts/tests/single_owner_account.rs, starknet-contract/tests/contract_deployment.rs, starknet-core/src/types/codegen.rs, starknet-core/src/types/message_status.rs, starknet-core/src/types/mod.rs, starknet-core/src/types/serde_impls.rs, starknet-providers/src/any.rs, starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/provider.rs, starknet-providers/src/sequencer/mod.rs, starknet-providers/src/sequencer/models/conversions.rs, starknet-providers/src/sequencer/provider.rs, starknet-providers/tests/jsonrpc.rs, starknet-tokio-tungstenite/README.md
Switches to JSON-RPC v0.9.x. All tests passing with current `pathfinder` at `main` branch (`2c1d0885f`).
=> feat: jsonrpc v0.9.0-rc.2 and starknet v0.14.0

Cargo.lock, Cargo.toml, README.md, starknet-accounts/Cargo.toml, starknet-contract/Cargo.toml, starknet-core/Cargo.toml, starknet-macros/Cargo.toml, starknet-providers/Cargo.toml, starknet-signers/Cargo.toml, starknet-tokio-tungstenite/Cargo.toml
Another RC for JSON-RPC v0.9 integration.
=> release: bump starknet to 0.17.0-rc.1 (and deps)

starknet-accounts/src/account/mod.rs, starknet-providers/src/jsonrpc/mod.rs, starknet-providers/src/provider.rs, starknet-providers/src/sequencer/provider.rs
=> chore: clippy lints

starknet-tokio-tungstenite/src/subscription.rs, starknet-tokio-tungstenite/tests/websocket.rs
Despite the ambiguity in specs StarkWare has clarified that reorg messages can be sent on the new subscription streams.
=> feat: allow reorgs in subscriptions
