xJonathanLEI/starknet-rs

- assets/CORE_README.md
- assets/PROVIDERS_README.md
This PR changes to use symbolic links for files in `./assets`.
`README.md` files from sub-crates are linked to a top-level `assets` folder since sub-crate folders are excluded when packaging `starknet`. However, hard links were incorrectly used, which are not supported by Git.
> fix: use symbolic links for files in `assets` folder

- .github/workflows/lint.yaml
This PR adds formatting checking for the following file types on top of `.rs` files:
- `md`
- `yaml` and `yml`
- `json`
`jq` is used for `json` files instead of `prettier` since `prettier` seems to accept multiple representations of the same `json` file in some cases.
> Add format checking for md, yaml, and json files

- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer_gateway.rs
The feeder gateway client in `cairo-lang` has a [`get_last_batch_id` function](https://github.com/starkware-libs/cairo-lang/blob/master/src/services/everest/api/feeder_gateway/feeder_gateway_client.py#L17) that's missing in the lib. This PR adds it. The call itself [returns](https://alpha4.starknet.io/feeder_gateway/get_last_batch_id) a single number.
> feat: get_last_batch_id

- .github/workflows/audit.yml
- .github/workflows/test.yaml
- .github/workflows/udeps.yml
- starknet-core/Cargo.toml
Adds two new CI Actions, as discussed in #4:
1) Security audit check via the [audit-check](https://github.com/actions-rs/audit-check) action. It is set up to run periodically once a day (as opposed to it being triggered by a push to `master` on on a PR) because of a [limitation](https://github.com/actions-rs/audit-check#limitations) that the action can't be triggered if the PR is coming from a fork. I figure it's fine this way because of the release process.
2) Unused dependencies via [cargo-udeps](https://github.com/est31/cargo-udeps). There's no GH Action wrapper for the tool, so I just built it using `action-rs/toolchain`, similar to the `test` workflow. It runs on `nightly`.
I had a look at [cargo-deny](https://github.com/EmbarkStudios/cargo-deny-action) as mentioned in #4, but I …
> ci: audit and udeps

- .github/workflows/udeps.yml
Resolves #17 
I changed the cache step for the same as is used in the Test action, udeps [now take](https://github.com/xJonathanLEI/starknet-rs/runs/4768223668?check_suite_focus=true) about a minute 🥳
> ci: use rust-cache for udeps

- README.md
Now that #6 is done and contract deployment is fully working, we can update the feature checkbox in `README.md`.
This PR also adds an example code snippet for reading an artifact from file and deploying to testnet.
> docs: add contract deployment example to README

- .github/workflows/test.yaml
Resolves #23.
Going from stable & nightly on Ubuntu to 1) stable & nightly on Ubuntu, 2) stable and nightly on OS X 11, 3) stable & nightly on Win GNU and 4) stable and nightly on Win MSVC.
This way we probably cover all the major dev platforms.
> ci: run tests on OS X and Windows

- Cargo.lock
- starknet-core/Cargo.toml
- starknet-core/src/crypto.rs
- starknet-core/src/lib.rs
- starknet-crypto/src/field_element.rs
This PR adds a `compute_hash_on_elements` utility function to `starknet-core`. This function is useful for computing the sig hash for the account contract.
Code ported from #18 with the underlying crypto library replaced with `starknet-crypto`.
A new public function `to_bytes_le` was added to `starknet_crypto::FieldElement` to make this possible.
> feat: implement high-level Pedersen util in `starknet-core`

- starknet-core/src/crypto.rs
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/field_element.rs
This PR:
- implements `ecdsa_sign`, a safe wrapper over the low level `starknet_crypto::sign`;
- exposes `ZERO` and `ONE` constants on `starknet_crypto::FieldElement`;
- fixes a typo introduced in #38: `to_bytes_le` -> `to_bytes_be`.
> feat: implement `ecdsa_sign` in `starknet-core`

- Cargo.lock
- starknet-core/Cargo.toml
- starknet-core/src/lib.rs
- starknet-core/src/utils.rs
This PR ports `get_selector_from_name` from `cairo-lang`.
> feat: implement `get_selector_from_name`

- starknet-core/src/crypto.rs
- starknet-core/src/types/field_element/unsigned.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/utils.rs
- starknet-signers/src/key_pair.rs
- starknet-signers/src/lib.rs
Resolves task 3 of #13:
> replace `U256` and `H256` with `UnsignedFieldElement` in crypto functions
> refactor: remove `U256` and `H256` on all public APIs

- README.md
Resolves task 4 of #13:
> fix outdated examples in `README`
> docs: fix outdated example on `README`

- starknet-core/src/types/call_contract.rs
The `result` field in `CallContractResult` uses hex representation. This bug wasn't discovered during the `UnsignedFieldElement` refactor because there's no test case covering this functionality.
> fix: fix deserializer used for contract call result

- starknet-core/src/crypto.rs
Just checked the official `cairo-lang` implementation and turns out you can do `compute_hash_on_elements` on an empty array.
This PR fixes that. Now `compute_hash_on_element` is infallible and returns `UnsignedFieldElement` instead of `Result`.
> fix: fix Pedersen hash on empty slice

- Cargo.lock
- starknet-signers/Cargo.toml
- starknet-signers/src/lib.rs
- starknet-signers/src/local_wallet.rs
- starknet-signers/src/signer.rs
Resolves task 1 of #50:
> add `Signer` trait as abstraction over `SigningKey` and other future implementations
This PR:
- adds a new `Signer` trait;
- adds a new type `LocalWallet` which wraps `SigningKey` and implements `Signer`.
In `ethers-rs`, the `address` method is synchronous, forcing all implementations that are asynchronous in nature to pre-fetch the address in their constructor, even if the user doesn't want to know the address. I took a different approach and made it `async` and free implementations from eagerly loading the address.
> feat: add `Signer` trait

- starknet-core/src/types/field_element/unsigned.rs
This PR implements addition, subtraction, and multiplication between `UnsignedFieldElement`'s.
It makes it much easier to do something like "increasing nonce by one".
Division is left out on purpose for a future PR, as it needs to align with the somehow strange behavior of Cairo.
> feat: implement simple math operations for `UnsignedFieldElement`

- README.md
- starknet-accounts/src/account.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/block.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer_gateway.rs
This PR replaces the use of `Option<BlockId>` with an explicit `BlockId::Latest` variant, as discussed in point 4) in #53.
> feat: explicit BlockId::Latest

- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
This PR skips 3 tests that hit the alpha testnet. Based on Henri's request in the Telegram group, I figured it's better to skip them completely rather then just ignore failures in the CI process.
> ci: skip alpha-goerli integration tests

- Cargo.lock
- starknet-core/src/types/field_element/unsigned.rs
- starknet-crypto/Cargo.toml
- starknet-crypto/benches/ecdsa_get_public_key.rs
- starknet-crypto/benches/ecdsa_sign.rs
- starknet-crypto/benches/ecdsa_verify.rs
- starknet-crypto/benches/pedersen_hash.rs
- starknet-crypto/benches/rfc6979_generate_k.rs
- starknet-crypto/src/ec_point.rs
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/field_element.rs
- starknet-crypto/src/field_element/fr.rs
- starknet-crypto/src/field_element/mod.rs
- starknet-crypto/src/lib.rs
- starknet-crypto/src/pedersen_hash.rs
- starknet-crypto/src/rfc6979.rs
- starknet-crypto/src/test_utils.rs
Resolves task 1 of #61:
> replace `ff` with `ark-ff` in `starknet-crypto` to make sure crypto primitives are properly upheld
> feat: replace `ff` with `ark-ff`

- Cargo.lock
- starknet-contract/Cargo.toml
- starknet-contract/src/artifact.rs
- starknet-core/Cargo.toml
- starknet-core/src/serde/unsigned_field_element.rs
- starknet-core/src/types/block.rs
- starknet-core/src/types/call_contract.rs
- starknet-core/src/types/contract_code.rs
- starknet-core/src/types/transaction.rs
- starknet-core/src/types/transaction_receipt.rs
- starknet-core/src/types/transaction_request.rs
- starknet-providers/Cargo.toml
- starknet-providers/src/sequencer_gateway.rs
This PR replaces `serde` modules with `serde_with` traits.
When working on #62, I encountered a type (`storage_diffs` from `get_state_update`) that uses `UnsignedFieldElement` as a `HashMap` key. To deserialize this type under the existing `serde` solution, I'll have to build yet another module that targets `HashMap<UnsignedFieldElement, _>` specifically, similar to what's been done with `Vec<UnsignedFieldElement>`. That's really annoying and makes code very ugly. So I've decided to use the magic from `serde_with` to solve it for good.
> refactor: adopt `serde_with`

- README.md
This PR fixes an example on README broken by #66.
> doc: fix README example

- README.md
OpenZeppelin restructured their repo so the `IAccount` link no longer works. I don't really want to use a permalink here as `IAccount` can evolve over time.
> doc: fix broken `IAccount` link on README

- starknet-ff/src/lib.rs
Resolves #74.
This PR fixes the critical bug of incorrect decimal representation of `FieldElement`.
> fix: incorrect `FieldElement` decimal formatting

- .github/workflows/test.yaml
- Cargo.lock
- starknet-core/Cargo.toml
- starknet-core/src/crypto.rs
- starknet-core/src/serde/unsigned_field_element.rs
- starknet-core/src/types/block.rs
- starknet-core/src/types/contract_addresses.rs
- starknet-core/src/types/contract_artifact.rs
- starknet-core/src/types/contract_code.rs
- starknet-core/src/types/state_update.rs
- starknet-core/src/types/transaction.rs
- starknet-core/src/types/transaction_receipt.rs
- starknet-core/src/utils.rs
- starknet-crypto/Cargo.toml
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/pedersen_hash.rs
- starknet-crypto/src/rfc6979.rs
- starknet-ff/Cargo.toml
- starknet-ff/src/lib.rs
- starknet-signers/Cargo.toml
- starknet-signers/src/key_pair.rs
This PR:
- makes all `#[test]` tests runnable for `wasm32-unknown-unknown` through `wasm-bindgen-test`; and
- adds yet another CI pipeline for running these tests via `wasm-pack test`.
We have added wasm-specific code for the WebAssembly support, so it's important we keep testing stuff under wasm too.
> ci: add CI pipeline for running WASM tests

- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
This reverts #59
I feel the testnet reliability has improved since so we can let those live tests run again.
> ci: run integration tests again

- .github/workflows/test.yaml
Looks like our CI pipeline doesn't test building for `wasm32-unknown-unknown`.
> ci: test building for WASM

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- starknet-core/src/crypto.rs
- starknet-crypto/src/ecdsa.rs
- starknet-signers/src/key_pair.rs
I just realized our CI has not been checking non-default targets like tests and benches. This PR fixes it along with some clippy warnings discovered.
> ci: run clippy checks on all targets

- starknet-core/src/utils.rs
This PR adds a simple utility function for converting [Cairo short strings](https://www.cairo-lang.org/docs/how_cairo_works/consts.html#short-string-literals) to `FieldElement`.
> feat: add util function for converting Cairo string to felt

- examples/mint_tokens.rs
- starknet-accounts/src/account.rs
- starknet-accounts/src/call.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
Resolves #101.
Now you can just do `account.execute(&[Call{...}]).send().await`, and inject `nonce` or `max_fee` if you want.
> feat: use builder pattern for `Account`

- starknet-accounts/src/single_owner.rs
- starknet-signers/src/key_pair.rs
- starknet-signers/src/local_wallet.rs
Aaaaaahhhh I am clooooniiiiinnng!!!!
The scope of the changes is limited to `starknet-signers` and `starknet-accounts` structs [excluding AttachedAccountCall] due to the immediate necessity encountered during the development of a personnal project.
:warning: Freshly converted rustacean :warning:
> Added Debug+Clone traits to signers and accounts structs

- starknet-providers/src/sequencer_gateway.rs
Added another function to create an instance of `SequencerGatewayProvider` with the appropriate args for a local dev node.
I am referring to the default parameters nile is [using](https://github.com/OpenZeppelin/nile/blob/main/src/nile/core/node.py).
> feat(providers): Instantiate localhost provider

- examples/deploy_contract.rs
- starknet-contract/src/factory.rs
- starknet-contract/tests/contract_deployment.rs
**This is a breaking change.**
`Provider` implementations are not cheap to clone, and they typically use HTTP clients that benefit from sharing a single instance. However, currently `ContractFactory` takes ownership of the provider, forcing code users to clone the provider instance.
This PR changes that by making it accept an `Arc`-wrapped provider instead.
> feat: wrap `provider` in `ContractFactory` with `Arc`

- README.md
We haven't been making releases for quite a while, and will probably keep it this way until the API surface stabilizes a bit more. This PR removes the crates.io installation instruction so that people won't accidentally use the ancient version.
> docs: remove crates.io installation instruction

- Cargo.lock
- starknet-contract/Cargo.toml
- starknet-contract/src/factory.rs
Similar to #97, this PR replaces the non-thread-safe RNG `thread_rng` with a thread-safe one, except this one actually works on all supported platforms.
> feat: use thread safe RNG for `ContractFactory`

- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer_gateway.rs
- starknet-signers/src/local_wallet.rs
- starknet-signers/src/signer.rs
This PR makes `Provider` and `Signer` `Send` so that they can be sent across threads.
This PR builds on the staled PR #92, but instead of simply dropping `?Send`, it only does so on non-wasm32 targets, otherwise wasm builds would break.
> feat: make `Provider` and `Signer` `Send`

- starknet-core/src/types/mod.rs
This PR exports `TransactionFailureReason` so that other applications can use it.
> feat: expose `TransactionFailureReason`

- starknet-core/src/serde/unsigned_field_element.rs
- starknet-core/src/types/transaction.rs
- starknet-core/test-data/raw_gateway_responses/get_transaction_status/manual/1_pending.txt
The value representing empty block hash in a pending transaction `get_transaction_status` response is `"None"`, unlike other responses.
This PR caters for this yet another inconsistency in the StarkNet sequencer API surface.
> fix: fix pending tx status deserialization

- Cargo.lock
- starknet-providers/Cargo.toml
- starknet-providers/src/provider.rs
This PR uses `auto_impl` to implement `Provider` for `&Provider`, `Box<T> where T: Provider` and `Arc<T> where T: Provider`.
Changes in #120 should be reverted after this PR, as it achieves essentially the same thing without imposing the restriction on using `Arc` for users.
> feat: implement `Provider` for smart pointers

- examples/deploy_contract.rs
- starknet-contract/src/factory.rs
- starknet-contract/tests/contract_deployment.rs
Thanks to #131, changes made in #120 can now be reverted while still allowing users to pass in `Arc`-wrapped instances.
This PR reverts changes made in #120.
> feat: remove `Arc` wrapper in `ContractFactory`

- starknet-accounts/src/account.rs
- starknet-accounts/src/single_owner.rs
Similar to #123, this PR makes `Account` `Send` on non-wasm targers so that it can be sent across threads.
> feat: make `Account` `Send`

- .github/workflows/lint.yaml
This PR adds caching to the `lint` CI pipeline to speed things up.
> ci: speed up lint CI with Rust cache

- starknet-core/src/types/contract_artifact.rs
- starknet-providers/src/sequencer_gateway.rs
This PR fixes yet another clashing of `untagged` and `arbitrary_precision`.
Reference: https://github.com/xJonathanLEI/starknet-rs/issues/76#issuecomment-1058193448
> fix: fix deserialization error on get_full_contract

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Releasing the following crates:
- `starknet-ff` v0.1.0
- `starknet-crypto` v0.1.0
- `starknet-core` v0.2.0
- `starknet-providers` v0.2.0
- `starknet-signers` v0.1.0
- `starknet-contract` v0.1.0
- `starknet-accounts` v0.1.0
- `starknet` v0.2.0
> release: publish packages to crates.io

- README.md
This PR adds back the installation instruction for `crates.io` now that we [released](https://github.com/xJonathanLEI/starknet-rs/pull/150) some reasonably-up-to-date code.
> docs: add back crates.io instruction

- starknet-core/src/types/mod.rs
Block status is also needed when interacting with the new json rpc.﻿
> feat: export BlockStatus

- Cargo.lock
- Cargo.toml
- README.md
- examples/jsonrpc.rs
- starknet-providers/Cargo.toml
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/transports/http.rs
- starknet-providers/src/jsonrpc/transports/mod.rs
- starknet-providers/src/lib.rs
- starknet-providers/tests/jsonrpc.rs
This PR partially implements #77 by adding a basic JSON-RPC client over HTTP.
Currently, the client only implements a single method `starknet_blockNumber`, with more methods to be implemented by future PRs.
> feat: implement basic JSON-RPC client

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
This PR partially implements #77 by implementing the `starknet_call` JSON-RPC method.
> feat(jsonrpc): implement starknet_call

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/src/jsonrpc/models/serde_impls.rs
- starknet-providers/tests/jsonrpc.rs
This PR partially implements #77 by adding support for the following methods:
- `starknet_chainId`
- `starknet_syncing`
- `starknet_getStorageAt`
> feat(jsonrpc): implement more JSON-RPC methods

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
This PR partially implements #77 by adding support for the following methods:
- `starknet_getBlockByHash`
- `starknet_getBlockByNumber`
> feat(jsonrpc): implement block query methods

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
This PR partially implements #77 by adding support for the following methods:
- `starknet_getTransactionReceipt`
- `starknet_getBlockTransactionCountByHash`
- `starknet_getBlockTransactionCountByNumber`
- `starknet_getEvents`
> feat(jsonrpc): implement remaining query methods

- starknet-core/src/serde/unsigned_field_element.rs
This PR removes the zero padding when serializing `FieldElement` as `UfeHex`. It's a breaking change for applications relying on this behavior.
> feat: remove zero padding for `UfeHex` serialization

- Cargo.lock
- starknet-providers/Cargo.toml
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
This PR partially implements #77 by adding support for the following methods:
- `starknet_addInvokeTransaction`
- `starknet_addDeclareTransaction`
- `starknet_addDeployTransaction`
> feat(jsonrpc): implement write methods

- README.md
Resolves #77.
We can now declare JSON-RPC support as all methods currently implemented by `pathfinder` are supported.
Support for new methods will be added as they are implemented by `pathfinder`.
> docs: declare JSON-RPC support in README

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
This PR changes `call()` signature to accept `AsRef<FunctionCall>` so that both `FunctionCall` and `&FunctionCall` can be accepted.
> feat(jsonrpc): use AsRef for call()

- starknet-providers/tests/jsonrpc.rs
This PR changes the RPC node used for integration tests to: https://starknet-goerli.rpc.zklend.com/ since the one we're using right now fails with 502 for `starknet_call` calls, possibly related to: https://github.com/eqlabs/pathfinder/issues/354
> test: switch to RPC node hosted by zkLend

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- README.md
- assets/MACROS_README.md
- src/lib.rs
- starknet-ff/src/lib.rs
- starknet-macros/Cargo.toml
- starknet-macros/README.md
- starknet-macros/src/lib.rs
- tests/macros.rs
This PR adds a proc macro `selector` so that:
- users no longer need to call `unwrap()` on `get_selector_from_name` for string literals; and
- selector values can now be `const`.
> feat: add macros crate with `selector` macro

- Cargo.lock
- Cargo.toml
- starknet-core/Cargo.toml
- starknet-ff/Cargo.toml
- starknet-ff/src/lib.rs
This PR adds `bigdecimal` integration to `starknet-ff` as an optional feature. `FieldElement` can now be interpreted as decimal numbers.
> feat: support FieldElement to BigDecimal conversion

- starknet-macros/src/lib.rs
- tests/macros.rs
This PR adds 2 new macros `felt_dec` and `felt_hex` for constructing `FieldElement` at compile time.
> feat: add macros for FieldElement literals

- starknet-macros/src/lib.rs
- tests/macros.rs
This PR adds another macro `felt` that accepts both decimal and hexadecimal representations.
> feat: add `felt` macro

- starknet-ff/src/lib.rs
This PR implements `BitAnd` and `BitOr` for `FieldElement`, useful for bitmap manipulation.
> feat: implement bitwise and & or operations for `FieldElement`

- starknet-core/src/serde/byte_array.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
`pathfinder` just released [v0.2.4](https://github.com/eqlabs/pathfinder/releases/tag/v0.2.4-alpha) aligning the `program` field type with the specs. This PR follows that change.
> fix(jsonrpc): ContractClass program field type

- README.md
- examples/sequencer_erc20_balance.rs
This PR adds an example for callling view functions via the sequencer gateway. It also uses macros for removing the need to call `unwrap()` in some cases.
> docs: add example for calling view function via sequencer gateway

- README.md
> docs: bump supported StarkNet version to 0.9.1

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
Resolves #200.
**:warning: This PR contains breaking changes since the spec itself introduced many such changes :warning:**
The official StarkNet JSON-RPC specification had been quite messy and inconsistent until the v0.1.0 release, which was why `starknet-rs` didn't attempt to catch up with the spec before. However, with the v0.1.0 release, despite some small issues, the quality of the spec has improved drastically. `pathfinder` also supported this spec version in their [v0.3.0 release](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha), with minor deviations:
- the `starknet_protocolVersion` method is not implemented by design (method to be removed in spec v0.2.0); and
- incorrect param names in `starknet_getEvents`: https://github.com/eqlabs/pathfinder/issues/536 (this …
> feat(jsonrpc): support specification v0.1.0

- README.md
This PR adds yet another badge to README showing the supported JSON-RPC specification version, linking to the spec repo with the specific version tag.
> docs: add supported JSON-RPC spec version to README

- starknet-providers/src/jsonrpc/models/mod.rs
This PR adds the `L1_HANDLER` transaction type introduced in [pathfinder 0.3.2](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.2). The lack of this type has been causing CI failures.
Note that technically this is a divergence from JSON-RPC spec 0.1.0, as this type is not included in that version.
> fix(jsonrpc): L1_HANDLER transaction type

- examples/sequencer_erc20_balance.rs
- starknet-accounts/src/single_owner.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/transaction_request.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer_gateway.rs
This PR further resolves API changes from StarkNet v0.10.1, on top of the work already done in #206:
- `call_contract`
Uses a new struct `CallFunction` for request body, which essentially removes `signature` and `max_fee` compared to the type used before.
Note that technically the sequencer run by StarkWare seems to still accept these fields, but they've [changed]() the client to not send those fields so I'm aligning the behavior here. To get call result using those fields, users can use the new `simulate_transaction` to be supported in another PR.
- `estimate_fee`
This method now accepts declare transactions on top of the already supported invoke transactions.
> feat: resolve sequencer API changes

- .github/workflows/lint.yaml
- starknet-core/src/crypto.rs
- starknet-core/src/types/block.rs
- starknet-core/src/types/starknet_error.rs
- starknet-core/src/types/trace.rs
- starknet-core/src/types/transaction.rs
- starknet-core/src/types/transaction_receipt.rs
Turns out the linting CI workflow ignores clippy warnings. This PR fixes that and resolves some existing clippy warnings.
> chore: resolve clippy warnings

- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/transaction_request.rs
- starknet-providers/tests/sequencer_goerli.rs
This PR adds support for `invoke` transaction v1, partially resolves task 3 of #207:
> abandon v0 transaction type in favor of v1
> feat: support v1 invoke transaction

- starknet-core/src/types/contract_artifact.rs
- starknet-core/src/types/contract_code.rs
- starknet-core/src/types/transaction_request.rs
- starknet-providers/src/sequencer_gateway.rs
Resolves #216.
This PR makes all necessary changes to make sure the JSON representation (including `debug_info`, though it's irrelevant for class hash computation) generated from this library matches char-by-char of those generated by `cairo-lang`. Notably, a test case `test_artifact_json_equivalence()` has been added to make sure we never break this equivalence.
> feat: same contract class json serialization as cairo-lang

- starknet-core/src/serde/json/mod.rs
- starknet-core/src/serde/mod.rs
- starknet-core/src/types/contract_artifact.rs
Building on top of #216, this PR implements local contract class hash calculation that outputs the exact same class hash as `cairo-lang` when given the same artifact (see the 2 new test cases `test_contract_class_hash` and `test_contract_hinted_class_hash`.
A special JSON formatter `PythonicJsonFormatter` has been introduced to emit the same not-so-compact JSON representation as in Python. Without this we would be getting a different `hinted_class_hash`.
It's worth noting that calling `class_hash()` on large contracts is currently very slow, especially in debug mode. This is mostly due to the slow Pedersen hash implementation in `starknet-crypto`. We need to solve this performance issue, probably starting by picking up the work in #35.
> feat: contract class hash calculation

- Cargo.lock
- README.md
- examples/declare_contract.rs
- examples/deploy_contract.rs
- starknet-accounts/Cargo.toml
- starknet-accounts/src/account.rs
- starknet-accounts/src/lib.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/test-data
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/Cargo.toml
- starknet-contract/src/factory.rs
- starknet-contract/src/lib.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-core/Cargo.toml
- starknet-core/src/types/contract_artifact.rs
- starknet-core/src/types/transaction_request.rs
Together with #215, resolves task 3 of #207:
> abandon v0 transaction type in favor of v1
This PR makes a lot of breaking changes, among others:
- it's no longer possible to send v0 `declare` transactions; and
- `ContractFactory` no longer offers `declare()` - declarations must go through `Account`.
You should update your codebase to work with these changes as the old v0 transaction type will be removed on live networks soon. It's technically possible for this library to support both v0 and v1 transactions at the same time, but it's deemed unnecessary as the old version is going away soon.
> feat: support v1 declare transaction

- starknet-crypto/src/ecdsa.rs
This PR fixes a new Clippy warning likely introduced in Rust 1.64.0.
> chore: fix clippy warnings

- starknet-accounts/src/account.rs
- starknet-accounts/src/single_owner.rs
Currently, the fee estimate buffer is hard-coded to 10%: whenever `max_fee` is not specified, the library estimates the fee via a call to the sequencer, and then adds 10% to it.
This PR makes this buffer value configurable, so you can now do something like:
```rust
account.execute(...).fee_estimate_multiplier(1.5).send().await
```
to make the buffer 50% instead, for example.
> feat: make fee estimate buffer configurable

- Cargo.lock
- starknet-core/Cargo.toml
- starknet-core/README.md
- starknet-core/benches/class_hash.rs
This PR adds a benchmark for `class_hash` calculation using the latest OpenZeppelin account contract. The current result is around 1.4 seconds on my machine with decent hardware, which is far from ideal.
#35 should significantly improve the performance on this.
> chore: add benchmark for class hash calculation

- starknet-core/README.md
- starknet-crypto/README.md
- starknet-crypto/src/ec_point.rs
- starknet-crypto/src/pedersen_hash.rs
- starknet-ff/src/lib.rs
Resolves #35.
This PR significantly improves the Pedersen hash performance by around 110% (2.81ms -> 0.23ms) by using projective points (with code taken from `pathfinder`, as already mentioned in the linked issue).
Class hash calculation has also been improved by around the same multiple.
> perf: use projective points for Pedersen hash

- README.md
- examples/starknet-wasm/README.md
This PR adds instructions for running the WebAssembly example. Hopefully it makes running `starknet-rs` in browser easier.
> docs: instructions for running the wasm example

- starknet-crypto/src/ec_point.rs
- starknet-crypto/src/pedersen_hash.rs
This PR changes to use in-place mutation for EC point types to reduce copys and better align with the `pathfinder` implementation so that we can port updates easier.
> refactor: mutate EcPoint and ProjectivePoint in-place

- BENCHMARK.md
- Cargo.lock
- README.md
- scripts/build_bench_wasm.sh
- scripts/run_bench_wasm.sh
- starknet-core/Cargo.toml
- starknet-core/README.md
- starknet-crypto/Cargo.toml
- starknet-crypto/README.md
Resolves #239.
This PR bumps `criterion` to `0.4.0` and adds benchmark results for `wasmer`, `wasmtime`, and Node.js (via `wasmer-js`).
Now that we have multiple targets, it makes more sense to present the benchmark results in a tabular form. It will be done in a future PR.
> chore: add wasm benchmark scripts and results

- Cargo.lock
- Cargo.toml
- starknet-core/README.md
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto-codegen/README.md
- starknet-crypto-codegen/src/lib.rs
- starknet-crypto/Cargo.toml
- starknet-crypto/README.md
- starknet-crypto/src/lib.rs
- starknet-crypto/src/pedersen_hash.rs
- starknet-crypto/src/pedersen_points.rs
- starknet-curve/src/ec_point.rs
Resolves #236.
The Pedersen hash performance has been significantly improved. Time per hash operation changed from `224.41 µs` to `31.988 µs`.
> perf: pedersen hash lookup tables

- starknet-crypto-codegen/src/lib.rs
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/pedersen_hash.rs
- starknet-curve/src/ec_point.rs
This PR replaces functions of `AffinePoint` and `ProjectivePoint` with `std::ops` implementations whenever possible. This is done to clean up the public API before publishing the first release.
> refactor: use ops traits for ec point types

- Cargo.lock
- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/src/lib.rs
- starknet-crypto/Cargo.toml
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/pedersen_hash.rs
- starknet-curve/src/ec_point.rs
- starknet-signers/Cargo.toml
The `starknet-crypto` crate version available on crates.io right now is around 100x slower than the current `master` head. It's time to release a new version so that projects stuck with crates.io (e.g. they also want to publish on crates.io) can take advantage of the performance gains.
- `starknet-ff`: `0.1.0` -> `0.2.0` - breaking changes on an error type
- `starknet-curve`: `0.1.0` - new crate
- `starknet-crypto-codegen`: `0.1.0` - new crate
- `starknet-crypto`: `0.1.0` -> `0.2.0` - there's zero breaking change on the lib itself, but since it re-exports `starknet-ff`, its public API has technically changed
> release: bump starknet-crypto to 0.2.0 (and deps)

- starknet-contract/tests/contract_deployment.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/codegen.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/tests/jsonrpc.rs
Resolves #244.
Supersedes #251.
While the work in #251 by @Matthew-Herman was quite complete, I decided to build on it with a new approach and implement codegen from the specs instead:
- it helps reduce future maintenance effort;
- it helps make sure we're not accidentally deviating from the specs.
The codegen tool is available [here](https://github.com/xJonathanLEI/starknet-jsonrpc-codegen).
Technically we're not directly deriving everything from the specs though, for some reasons:
- the specs itself isn't completely correct: https://github.com/starkware-libs/starknet-specs/pull/64;
- some semantics are not captured by the specs (e.g. the `type` field value is directly linked to the variant, but the specs doesn't declare the relationship);
- some types are too complicated to be …
> feat(jsonrpc): update to support spec v0.2.1

- README.md
A simple version bump following the test data update in #258.
> docs: bump supported StarkNet version to 0.10.3

- starknet-core/src/chain_id.rs
This PR adds the chain ID constant for testnet 2 following the chain ID change. This is the same diff that got dropped as part of #233.
> feat: chain id for testnet 2

- examples/deploy_contract.rs
- starknet-accounts/src/single_owner.rs
- starknet-contract/src/factory.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer_gateway.rs
A `token` param was used for the `add_transaction` method as `mainnet-alpha` required a whitelist for deploy/declare transactions.
This restriction has been lifted as `mainnet-alpha` upgraded to v0.10.3. This PR removes the use of the optional token for good since there's no more use case for it.
> feat: remove token for add_transaction method

- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/src/jsonrpc/models/serde_impls.rs
Enum variants in JSON-RPC models are tagged even when individually serialized, which is an intentional behavior since I don't want to force users to wrap variant values inside their higher level enum type just to get the tag fields (e.g. `type`, `version`) serialized. That's why you can see a lot of custom serde impl blocks in model code.
However, there's currently a bug on the enum level causing the tag fields to be serialized twice when serializing from the enum level. This PR fixes it by manually implementing the `Serialize` traits for these types.
> fix(jsonrpc): duplicate fields in tagged enum serialization

- starknet-core/src/serde/byte_array.rs
This PR resolves new clippy warnings introduced in Rust `1.66.0`.
> chore: make clippy happy

- starknet-ff/src/lib.rs
This PR refactors `Deserialize` trait of `FieldElement` using `from_str` so that can deserialize both hex and decimal string.
> refactor: use from_str when deserializing FieldElement

- starknet-accounts/src/account/execution.rs
- starknet-accounts/tests/single_owner_account.rs
Resolves #252.
You can now do something like:
```rust
account
.execute(vec![...])
.simulate()
.await
```
To get the trace of the execution without actually sending it out.
> feat: simulate account execution

- starknet-providers/src/jsonrpc/transports/http.rs
- starknet-providers/src/sequencer_gateway.rs
This PR adds a new `new_with_client` constructor to types `SequencerGatewayProvider` and `HttpTransport`, making it possible to customize the HTTP client.
One example use case is to set HTTP timeout, which wasn't possible before this PR.
> feat: bring your own http client

- starknet-core/src/types/starknet_error.rs
This PR adds support for deserializing the `INVALID_TRANSACTION_NONCE` error code.
> feat: error code `INVALID_TRANSACTION_NONCE`

- starknet-accounts/src/account/mod.rs
This PR implements `Account` and `ConnectedAccount` for their smart pointer wrapper types. This allows one to use a smart pointer when an `Account` impl is expected, avoiding unnecessary clones.
`auto_impl` is not used cuz it doesn't seem to work when any trait function wraps the type itself.
> feat: implement account traits for ref types

- starknet-core/src/types/mod.rs
- starknet-core/src/types/transaction_request.rs
This PR removes the type used for sending out `deploy` transactions since it's no longer possible to send them on any live network.
> feat: remove deploy transaction request

- README.md
- examples/deploy_argent_account.rs
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/src/factory/open_zeppelin.rs
- starknet-accounts/src/lib.rs
Implements the second half of #232. Closes #232.
This PR:
- adds a new trait `AccountFactory` which enables deploying pre-funded account through the `DeployAccount` transaction type; and
- implements the trait for Argent X and OpenZeppelin account contracts; and
- adds a new example of deploying an Argent X account with this new construct.
With this new feature, users can calculate the target address with a deployment, somehow fund the account, and proceed with the actual deployment transaction, as demonstrated in the example added.
No integration test case has been added as we only test against live environments (no local dev net) and testing this feature requires pre-funding addresses. It has been tested with the example code though.
> feat: account contract deployment

- starknet-macros/src/lib.rs
This PR adds yet another macro `short_string` for building Cairo short strings at compile time.
> feat: `short_string!()` macro for compile-time Cairo short strings

- starknet-macros/Cargo.toml
- starknet-macros/src/lib.rs
Currently macros in `starknet-macros` are hard-coded to use the full path for the `FieldElement` type from the `starknet` crate so that users won't have to bring `FieldElement` into scope for the macros to work. However, this is an issue for our subcrates themselves: they don't have access to the parent `starknet` crate.
This PR adds an optional feature `use_imported_type` to the `starknet-macros` crate which requires users to bring `FieldElement` into scope, and in turn, doesn't require `starknet` to be on the crate import list.
This is so that we can replace all our const `FieldElement` definitions with macros (no more magic mont reprs).
> feat: allow imported `FieldElement` type in macros

- starknet-core/src/serde/mod.rs
- starknet-core/src/serde/num_hex.rs
- starknet-core/src/types/contract_artifact.rs
- starknet-core/src/types/contract_code.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/transaction_request.rs
- starknet-providers/tests/jsonrpc.rs
This PR makes a few minor changes regarding contract related types in `starknet-core`:
- `ContractDefinition` now implements `Clone`;
- `EntryPoint::offset` is now `u64` instead of `FieldElement` to match with JSON-RPC;
- a few missing type exports have bee fixed.
> chore: fix issues with contract types

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/codegen.rs
- starknet-providers/tests/jsonrpc.rs
This PR adds support for JSON-RPC error code decoding, parsing it into a Rust enum that can be pattern matched.
> feat(jsonrpc): error code decoding

- starknet-accounts/src/factory/mod.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/conversions.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/src/jsonrpc/provider.rs
- starknet-providers/src/jsonrpc/transports/mod.rs
This PR implements `Provider` for `JsonRpcClient`.
Note that this is just a partial implementation. Only 3 methods necessary for using it as an `Account` or `AccountFactory` backend have been implemented:
- `add_transaction`
- `estimate_fee`
- `get_nonce`
Calling any other method returns an unsupported error.
> feat(jsonrpc): partially implement `Provider` for jsonrpc client

- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/mod.rs
This PR helps make sure developers don't forget to call `send()` on the intermediate types resulting from `execute()`, `declare()`, and `deploy()`. It's now a compiler warning to not use them.
> feat: add `must_use` on intermediate types

- Cargo.toml
- README.md
- src/lib.rs
- starknet-accounts/Cargo.toml
- starknet-accounts/README.md
- starknet-accounts/src/account/mod.rs
- starknet-contract/Cargo.toml
- starknet-core/README.md
- starknet-core/src/types/block.rs
- starknet-core/src/types/fee.rs
- starknet-core/src/types/trace.rs
- starknet-core/src/types/transaction_request.rs
- starknet-core/src/utils.rs
- starknet-core/test-data/raw_gateway_responses/generate_responses.sh
- starknet-crypto/Cargo.toml
- starknet-crypto/README.md
- starknet-curve/README.md
- starknet-ff/Cargo.toml
- starknet-ff/README.md
- starknet-providers/README.md
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/codegen.rs
- starknet-signers/Cargo.toml
- starknet-signers/README.md
Changes the spelling of "StarkNet" from "StarkNet" to "Starknet" everywhere in the codebase following the recommendations in [this SNIP](https://community.starknet.io/t/snip-naming-convention-starknet-not-starknet).
> chore: change "StarkNet" to "Starknet"

- starknet-ff/src/lib.rs
Adds `from_byte_slice_be` to `FieldElement`. Useful when you have a `Vec` for example.
> feat: convert byte slice to `FieldElement`

- Cargo.lock
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-core/src/types/state_update.rs
- starknet-core/src/types/trace.rs
- starknet-core/src/types/transaction.rs
- starknet-core/src/types/transaction_receipt.rs
- starknet-providers/Cargo.toml
- starknet-providers/src/jsonrpc/models/codegen.rs
This PR bumps the `serde_with` dependency to `2.2.0` and removes the `#[serde(default)]` attribute on all `#[serde_with = "Option<...>"]` as it's [no longer necessary](https://github.com/jonasbb/serde_with/releases/tag/v2.0.0) with the updated version.
> chore: bump `serde_with` to 2.2.0

- Cargo.lock
- starknet-crypto/Cargo.toml
- starknet-crypto/src/rfc6979.rs
- starknet-ff/Cargo.toml
- starknet-ff/src/lib.rs
Keeps our crypto dependencies up to date (`ark-ff` 0.4.0 will be handled in a separate PR).
> chore: bump some crypto-related deps

- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/trace.rs
- starknet-providers/tests/sequencer_goerli.rs
Turns out all fields except `signature` should be optional in transaction traces as `DECLARE` transactions don't have any of those:
```
$ curl "https://alpha-mainnet.starknet.io/feeder_gateway/get_transaction_trace?transactionHash=0x049385a99d26e93ed8eb09471892e5225e4946e79d8800c9044c0c0c2f7506f8"
{"signature": []}
```
> fix: function_invocation should be optional

- Cargo.lock
- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-ff/Cargo.toml
- starknet-signers/Cargo.toml
With #306 merged, let's publish another version for `starknet-crypto` to crates.io so that downstream `no_std` applications can use it.
Hiding existing functionalities behind feature gates is a breaking change, so we need to bump minor version here: `0.2.0` -> `0.3.0`.
> release: bump starknet-crypto to 0.3.0 (and deps)

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
`no_std` support was added in #306 but the CI isn't enforcing it now. This PR adds building and linting of `no_std` feature combinations to make sure we don't accidentally break it.
> ci: build and lint no_std

- examples/starknet-wasm/webpack.config.js
We've been using the `development` mode for the Webpack wasm example. The `wasm-pack` plugin inherits the setting and uses `--debug` for compiling the wasm module, which gives a bad impression on the size and performance of the resulting module.
This PR changes to use `production` mode instead. The built wasm module before this change is **270 KB** in size and it's now only **51 KB**.
> docs: use production mode for wasm example

- starknet-ff/src/lib.rs
Makes it easy to do felt arithmetic. Now you can do:
```rust
let mut value = felt!("0x123");
value += felt!("0x234");
```
instead of:
```rust
let mut value = felt!("0x123");
value = value + felt!("0x234");
```
> feat: implement ops assign traits for `FieldElement`

- starknet-crypto-codegen/src/poseidon/mod.rs
- starknet-crypto/README.md
- starknet-crypto/src/poseidon_hash.rs
https://github.com/eqlabs/pathfinder/pull/914 is now merged with minor changes since we ported the code over. This PR port those minor additional changes (a single field name change) and updates the commit mark to `00a1a74a90a7b8a7f1d07ac3e616be1cb39cf8f1`.
> chore: sync poseidon code to pathfinder `00a1a74a`

- starknet-core/src/types/contract/mod.rs
Partially implements task 3 of #313:
> support computing class hashes of Cairo 1 contracts
Implememts class hash calculation for the _compiled class_. A bit more context as this could be confusing:
Right now there are 3 types of contract classes, each with its own different way of calculating the class hash:
1. Sierra class (not implemented yet)
2. Compiled (CASM) class (this PR)
3. Legacy class (Cairo 0 contracts, implmeneted)
In theory, only `1` would be needed for contract declaration. However, as Sierra -> CASM compilation hasn't heen proven yet, and likely won't be in the near future (according to StarkWare), users need to also generate and sign the class hash for `2` to stop the sequencer from claiming any arbitrary code to be the compilation result. This PR enables just that, which …
> feat: compiled class hash calculation

- starknet-crypto/src/lib.rs
- starknet-crypto/src/poseidon_hash.rs
Turns out there are use cases (like https://github.com/lambdaclass/cairo-rs/pull/875) that would need access to the Poisedon permutation function. `starknet-crypto` is supposed to expose low-level primitives and the function should be made public.
> feat: expose Poiseidon permutation function

- Cargo.lock
- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-ff/Cargo.toml
- starknet-signers/Cargo.toml
Making a new release for `starknet-crypto` as the Poseidon hash function becomes available, bumping `starknet-crypto` to `0.4.0`.
`starknet-ff` and `starknet-curve` were only bumped for patch version as no breaking changes were made.
> release: bump starknet-crypto to 0.4.0 (and deps)

- starknet-core/src/crypto.rs
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/lib.rs
- starknet-signers/src/key_pair.rs
Undoes the addition of the `v` field to `Signature` introduced in #315 by @greged93.
We don't want the `v` field in `Signature` because the same struct is also used by `starknet-core` for signature verification, which does not make use of `v`. The addition of the field forces users to supply a `v` value for that.
A new struct `ExtendedSignature` is added instead, which can be converted into `Signature`.
> feat: revert breaking change on `Signature`

- Cargo.lock
- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-signers/Cargo.toml
Technically we should release `0.5.0` as #322 was a breaking change. However, under romantic versioning, I'm just gonna bump the patch version because I've yanked `0.4.0` soon after release so that no one installs it by accident.
> release: bump starknet-crypto to 0.4.1

- starknet-crypto/src/ecdsa.rs
As pointed out in https://github.com/xJonathanLEI/starknet-rs/pull/322#discussion_r1132115169, `v` is missing from the `Display` implementation of `ExtendedSignature`). Thanks to @milancermak for spotting this!
> fix: missing v for Display impl for `ExtendedSignature`

- starknet-crypto/Cargo.toml
We should probably enable this by default. `no_std` users would disable all default features anyways.
> feat: enable feature signature-display by default

- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-signers/Cargo.toml
Enabling a feature by default is not a breaking change. Bumping patch version.
> release: bump starknet-crypto to 0.4.2

- .github/workflows/test.yaml
- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- examples/starknet-cxx/CMakeLists.txt
- examples/starknet-cxx/README.md
- examples/starknet-cxx/main.cpp
- examples/starknet-cxx/starknet-cxx/CMakeLists.txt
- examples/starknet-cxx/starknet-cxx/Cargo.toml
- examples/starknet-cxx/starknet-cxx/src/lib.rs
Resolves #325.
This PR adds a new example for using `starknet-crypto` from C++.
Given the state of the official C++ crypto library (see https://github.com/starkware-libs/crypto-cpp/issues/2), it probably makes sense to use `starknet-rs` from C++. Adding this example considering that the C++ audience might not be familiar with Rust.
> docs: add C++ example with cxx

- Cargo.lock
- examples/starknet-cxx/README.md
- examples/starknet-cxx/main.cpp
- examples/starknet-cxx/starknet-cxx/Cargo.toml
- examples/starknet-cxx/starknet-cxx/src/lib.rs
See #329.
It seems extremely easy for people to shoot themselves in the foot for using `starknet-crypto` directly, especially for developers not familiar with Rust - it's harder for them to inspect the code to see what's _really_ going on.
This PR changes to wrap `starknet-core` instead, and only expose the high-level `ecdsa_sign` function, which takes care of the `k` generation.
> docs: use starknet-core for the starknet-cxx example instead

- starknet-core/src/types/contract/mod.rs
- starknet-core/src/utils.rs
Resolves task 3 of #313:
> support computing class hashes of Cairo 1 contracts
With this PR the library is capable of calculating hashes for all 3 types of contract classes in existence.
Note that in this PR I'm hard-coding to use the Pythonic JSON formatting for the ABI to match the class hash calculated from the official `cairo-lang` CLI, just to make sure we're doing it right, but that's not necessary. In a future PR we should make the formatting plug-able with a `AbiFormatter` trait, allowing users to specify how the ABI should be formatted, including not uploading ABI at all (`VoidFormatter`?).
> feat: sierra class hash calculation

- Cargo.lock
- README.md
- examples/declare_cairo0_contract.rs
- examples/declare_cairo1_contract.rs
- starknet-accounts/Cargo.toml
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/lib.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/contract/mod.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/transaction_request.rs
- starknet-providers/src/jsonrpc/models/conversions.rs
- starknet-providers/src/jsonrpc/provider.rs
- starknet-providers/src/sequencer_gateway.rs
There you go. `DECLARE` v2 supported. It's now possible to declare Cairo 1 contracts with `starknet-rs`.
However, this only partially resolves task 4 of #313:
> support sending Declare v2 transactions
as JSON-RPC support is not enabled yet. With this PR declaration is only possible via the sequencer gateway.
This is because the current specs version (0.2.1) does not support `DECLARE` v2. We will need to manually patch the spec to make it work, which is quite some work, and I will deal with that in a separate PR.
> feat: support declare v2 transaction

- Cargo.lock
- starknet-accounts/Cargo.toml
- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/contract/mod.rs
- starknet-providers/Cargo.toml
- starknet-providers/src/jsonrpc/models/codegen.rs
- starknet-providers/src/jsonrpc/models/conversions.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/src/jsonrpc/models/serde_impls.rs
- starknet-providers/src/jsonrpc/provider.rs
- starknet-providers/tests/jsonrpc.rs
This PR adds `DECLARE` v2 support to JSON-RPC.
Together with #343, resolves task 4 of #313:
> support sending Declare v2 transactions
> feat(jsonrpc): declare v2 transaction

- starknet-providers/src/jsonrpc/models/codegen.rs
- starknet-providers/src/jsonrpc/models/mod.rs
- starknet-providers/src/jsonrpc/models/serde_impls.rs
This PR makes it possible to deserialize `BlockId`, which is useful for applications using `starknet-rs` on the server side.
> feat(jsonrpc): `BlockId` deserialization

- starknet-crypto/src/ecdsa.rs
Multiplication of EC points by scalars was the major bottleneck in that function. Converting the points to projective points first leads to 85% less time spent on the function according to Criterion.
> perf: projective points for verification of ECDSA

- starknet-core/README.md
- starknet-crypto/README.md
Re-running the benchmarks as a major improvement has been made to `ecdsa_verify` in #355.
Not sure why but wasm perf generally became twice as slow compared to last time we ran them... Definitely not relevant to #355 though. Will investigate later.
> docs: update benchmark results

- starknet-providers/tests/jsonrpc.rs
It looks like Infura has finally upgrade to `pathfinder` 0.5.3, unblocking the test cases we had to ignore before. This PR re-enables the 2 tests.
> test: re-enable jsonrpc class tests

- .github/workflows/test.yaml
- Cargo.lock
- starknet-ff/Cargo.toml
- starknet-ff/src/fr.rs
- starknet-ff/src/lib.rs
This PR bumps `ark-ff` to 0.4.0 and resolves all the breaking changes.
> chore: bump `ark-ff` to 0.4.2

- Cargo.lock
- starknet-crypto/Cargo.toml
- starknet-ff/Cargo.toml
- starknet-ff/src/lib.rs
Bumps `crypto-bigint` and resolves breaking changes.
> chore: bump `crypto-bigint` to 0.5.1

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
Somehow missed this during the account feature revamp. This allows setting a higher fee buffer without manually estimating fees first.
> feat: allow setting fee estimate multiplier

- starknet-accounts/src/factory/mod.rs
I missed `AccountDeployment` in #361. This PR adds the same `fee_estimate_multiplier()` function for `AccountDeployment` too.
> feat: setting fee estimate multiplier for `AccountDeployment`

- examples/declare_cairo0_contract.rs
- examples/declare_cairo1_contract.rs
- examples/deploy_contract.rs
- examples/mint_tokens.rs
- starknet-accounts/src/single_owner.rs
- starknet-core/src/types/block.rs
This PR enables setting the target block ID for `SingleOwnerAccount`. Currently, the account is hard-coded to make queries (for nonce and fees) against the latest block. With this change users can now specify a different one, for example the pending block.
I was reluctant to add this because the whole concept of a pending block will likely be removed anyways, but that's probably gonna take quite a while to happen, so here we go.
> feat: allow setting target block for account

- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/mod.rs
- starknet-providers/src/jsonrpc/transports/mod.rs
- starknet-providers/src/provider.rs
- starknet-signers/src/signer.rs
Makes the life of downstream application developers easier since they will have fewer constraints to write explicitly, unless there's a use case screwed by this that I'm not aware of.
> feat: restrict all error types to be Send + Sync

- starknet-core/src/crypto.rs
- starknet-crypto/src/ecdsa.rs
- starknet-crypto/src/error.rs
- starknet-curve/src/ec_point.rs
Fixes #365.
This PR fixes a panic when calling `verify()` or `recover()` in `starknet-crypto` as the library always assumed that inputs are valid.
Downstream applications should upgrade to `0.4.4` (to be published after this PR) asap to avoid invalid inputs from crashing them.
> fix: panic in ecdsa verify and recover

- starknet-crypto/Cargo.toml
- starknet-crypto/benches/ecdsa_recover.rs
- starknet-crypto/src/ecdsa.rs
Migrated all multiplications between EC points and field elements in ECDSA to projective points. Included a new benchmark for the `ecdsa_recover` function.
Refactored the `ecdsa_verify` changes too so all use a little helper to reduce boilerplate.
Results:
```
ecdsa_get_public_key    time:   [113.13 µs 113.20 µs 113.28 µs]
change: [-92.975% -92.959% -92.940%] (p = 0.00 < 0.05)
Performance has improved.
ecdsa_recover           time:   [412.73 µs 413.33 µs 414.48 µs]
change: [-88.145% -88.120% -88.082%] (p = 0.00 < 0.05)
Performance has improved.
ecdsa_sign              time:   [160.00 µs 160.06 µs 160.14 µs]
change: [-90.003% -89.985% -89.967%] (p = 0.00 < 0.05)
Performance has improved.
ecdsa_verify            time:   [412.61 µs 412.77 µs 412.98 µs]
change: [-3.8553% -1.8908% -0.5588%] (p …
```
> perf: projective point for ecdsa ops

- Cargo.lock
- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-signers/Cargo.toml
Makes another `starknet-crypto` release to make performance improvements from #368 available on crates.io.
> release: bump starknet-crypto to 0.5.1

- starknet-ff/src/lib.rs
Now you can finally do this:
```rust
let sum: FieldElement = [felt!("1"), felt!("2"), felt!("3")].iter().sum();
```
> feat: implement iter::Sum on FieldElement

- starknet-providers/src/any.rs
- starknet-providers/src/lib.rs
- starknet-providers/src/sequencer_gateway.rs
Currently, it's easy for downstream applications to make their code generic over any provider implementations simply by making their functions generic over the `Provider` trait (instead of the concrete impl type). They would then be able to swap out the impl at _compile time_ by changing the provider creation code.
However, to make applications generic over different impls at _runtime_ is cumbersome, as Rust does not (yet) allow `Box`ing a trait with associated types. AFAIK the only workaround is to build a wrapper type that exhausts all known variants. Instead of making all downstream applications repeat the same work, I'm adding a new `AnyProvider` struct to the library to make it easier for downstream devs.
Obviously this won't work with user-supplied `Provider` or even …
> feat: AnyProvider wrapper for all Provider impls

- starknet-providers/src/jsonrpc/models/conversions.rs
- starknet-providers/src/jsonrpc/provider.rs
Implements 3 new `Provider` functions for `JsonRpcClient`:
- `call_contract`
- `get_storage_at`
- `get_transaction_status`
This should make the jsonrpc client much more useful as a `Provider` impl.
Note that there's caveat though: `get_transaction_status` (or any other tx getter method) inherently doesn't work very well with jsonrpc due to the lack of tx mempool. Downstream applications might want to use the sequencer gateway client for those.
> feat(jsonrpc): better Provider trait coverage

- starknet-providers/src/jsonrpc/models/codegen.rs
The new codegen version applies type sorting, making it easier to compare future diffs. This commit itself makes zero actual code change.
> chore: regenerate jsonrpc model code

- README.md
- examples/parse_jsonrpc_request.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/transports/http.rs
This PR adds a new public type `JsonRpcRequest` for easy parsing of jsonrpc requests on the server side. A new example `parse_jsonrpc_request` has also been added to demonstrate how it would work. With this new type, jsonrpc server implementations would simply need to write handlers for the different data variants - no need to fiddle with parsing params or mapping request data types to methods names.
Do note that the automatic generation of response types hasn't been implemented yet, meaning server implementations would still need to manually put together the response types at the moment.
> feat(jsonrpc): server-side request parsing

- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/models/codegen.rs
Forgot to add the error code `InvalidContractClass` to the conversion trait impl. We should include this as part of the codegen.
> fix(jsonrpc): missing error code conversion

- Cargo.lock
- starknet-signers/Cargo.toml
- starknet-signers/src/key_pair.rs
- starknet-signers/src/lib.rs
Adds support for using the Ethereum keystore format:
```rust
SigningKey::from_keystore("./my-keystore.json", "my_password");
```
Adding this because `starkli` needs it, and apparently many other applications that need to send out transactions would find this a much better solution than feeding private keys in plain text.
> feat: web3 secret storage definition keystore support

- Cargo.lock
- starknet-signers/Cargo.toml
- starknet-signers/src/key_pair.rs
Supports cryptographically secure random `SigningKey` generation. This will be useful for generating new keystores in `starkli`.
> feat: random `SigningKey` generation

- starknet-providers/src/jsonrpc/models/codegen.rs
- starknet-providers/src/jsonrpc/models/conversions.rs
- starknet-providers/src/jsonrpc/models/mod.rs
Renaming a few jsonrpc types to make the upcoming full transition to jsonrpc easier. The new names match with the existing corresponding types in `starknet-core`.
> feat: regenerate jsonrpc model code for renames

- starknet-accounts/src/account/declaration.rs
- starknet-core/src/types/codegen.rs
These fields are heavy but are normally only used for serialization. Wrapping them in `Arc` helps avoid forcing callers to always supply the full owned instances. Alternatives include making these fields references or even generic over `AsRef<>`, but they all make these types harder to use. So using `Arc` looks like a good compromise.
> feat: wrap class fields with `Arc`

- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/contract/mod.rs
- starknet-core/src/types/conversions.rs
- starknet-core/src/types/mod.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/models/contract.rs
- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/mod.rs
- starknet-providers/src/sequencer/models/transaction.rs
- starknet-providers/src/sequencer/models/transaction_request.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
We moved the whole library to be jsonrpc-first in #385, but left out the implementation of the new `Provider` for `SequencerGatewayProvider` to make that PR still somewhat manageable. This PR implements almost all functions in `Provider` except the 2 below:
- `get_events`
- `add_deploy_transaction`
It's impossible to implement `get_events` and `add_deploy_transaction` is actually already gone (no longer in specs 0.3.0) anyways.
This PR also re-enables the sequencer-related test cases as the sequencer can now be actually used in places where `Provider` is expected.
> feat: implement `Provider` for `SequencerGatewayProvider`

- starknet-providers/src/sequencer/models/conversions.rs
This causes failure when using sequencer gateway as `Provider`.
> fix: DeployAccount receipt conversion

- starknet-core/src/types/codegen.rs
Currently the request types only support deserializing from params formatted as arrays, but the jsonrpc standard allows object-based params too.
> feat: object-based param deserialization

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/contract/legacy.rs
- starknet-core/src/types/contract/mod.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/requests.rs
- starknet-core/src/types/serde_impls.rs
- starknet-providers/src/any.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
Support for the jsonrpc spec version 0.3.0 has been completed and living in the `dev/jsonrpc_0_3_0` branch for a while. I was originally waiting on `pathfinder` to release a version to serve `v0.3` on the default path before merging this to `master`, but it seems to be taking a while, and the whole ecosystem seems to have largely embraced 0.3.0 anyways. So here we go, switching to 0.3.0 for good.
Users who want to stay at 0.2.x can use the last commit before this PR gets merged: https://github.com/xJonathanLEI/starknet-rs/commit/213489e171b3057a02eab9dedcd94a7a3b0df125
I think this makes more sense than forcing 0.3.0 users to use an unstable branch, now that the spec version itself has been officially released.
> feat(jsonrpc): switch to spec 0.3.0

- Cargo.lock
- Cargo.toml
- README.md
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-ff/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
It's been a while (1 year+) since anything other than `starknet-crypto` and its dependencies was last published on crates.io. Now that we've merged #385 and #396, which contain some of the biggest breaking changes, it seems to be a good timing to resume publishing to crates.io.
This PR bumps versions of all crates except for those that are already up to date.
> release: bump starknet to 0.3.0

- starknet-core/src/types/contract/legacy.rs
- starknet-core/src/types/contract/mod.rs
Now you can clone class types.
> feat: derive `Clone` for contract types

- starknet-accounts/tests/single_owner_account.rs
The `pathfinder` bug has been fixed and we no longer need to skip that test.
> test: re-enable ignored test case

- starknet-providers/src/sequencer/mod.rs
This happens when the sequencer cannot compile your Sierra class.
> fix(sequencer): missing err code `CompilationFailed`

- .github/workflows/udeps.yml
- Cargo.lock
The old version of `proc-macro2` no longer works with the latest nightly version of Rust.
> chore: fix proc-macro2 issues

- starknet-core/Cargo.toml
- starknet-core/src/types/contract/legacy.rs
- starknet-core/src/types/contract/mod.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/models/contract.rs
The `arbitrary_precision` feature from `serde_json` is used mostly because of how the Cairo 0 artifact represents big numbers in raw number format instead of string. Without this feature enabled the correct class hash could not be obtained.
However, the implementation of this feature is problematic and has been causing issues. Switching to `raw_value` wouldn't resolve those as `raw_value` suffers from the very same issues as `arbitrary_precision`. What's less bad about `raw_value` is that using it is opt-in - it doesn't pollute number decoding like `arbitrary_precision` does. This is important due to how Cargo resolves dependencies - dependants of this library might be forced to enable the `serde_json` feature.
Resolves #394.
> feat: use raw_value instead of arbitrary_precision

- starknet-core/src/types/contract/mod.rs
- starknet-core/test-data/contracts/cairo2/contracts/erc20.cairo
Same as a function, only the name is changing.
> fix: missing L1Handler abi type

- Cargo.lock
- starknet-core/Cargo.toml
- starknet-core/src/types/mod.rs
- starknet-providers/Cargo.toml
- starknet-providers/src/sequencer/models/contract_addresses.rs
- starknet-providers/src/sequencer/models/mod.rs
- starknet-providers/src/sequencer/models/trace.rs
- starknet-providers/src/sequencer/models/transaction_receipt.rs
- starknet-providers/src/sequencer/models/transaction_request.rs
- starknet-providers/tests/sequencer_goerli.rs
The type `L1Address` is only used in the sequencer client, so it makes more sense to put it in the `starknet-providers` crate.
In the future, we should add a `sequencer` feature to `starknet-providers` and hide this behind that as well.
> refactor: move `L1Address` to `starknet-providers`

- .github/workflows/test.yaml
- starknet-core/Cargo.toml
- starknet-core/src/crypto.rs
- starknet-core/src/lib.rs
- starknet-core/src/serde/byte_array.rs
- starknet-core/src/serde/num_hex.rs
- starknet-core/src/serde/unsigned_field_element.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/contract/legacy.rs
- starknet-core/src/types/contract/mod.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/serde_impls.rs
- starknet-core/src/utils.rs
Resolves #403.
Supersedes #415.
Adds a new `std` feature to `starknet-core` that's enabled by default. When disabled, the crate compiles in a `no_std` environment.
Compared to #415, this PR only disables Cairo 0 class compression under `no_std`. All other features work.
> feat: `no_std` support for `starknet-core`

- Cargo.lock
- Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
Removes the `bigdecimal` feature from `starknet-curve`, `starknet- crypto`, and `starknet-core`, as these crates just use/re-export the `starknet-ff` lib without being affected by the presence of `bigdecimal` anyways. There's no reason to have that feature. Users who do want to enable `bigdecimal` while using these crates need to manually import `starknet-ff`.
This feature still makes sense for `starknet` though, as it's designed to be a Just Works crate that's easy to consume.
> refactor: remove `bigdecimal` feature from crates

- Cargo.lock
- Cargo.toml
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Bumps all crates except `starknet-ff`. _patch_ or _minor_ is bumped depending on whether breaking changes have been introduced for any specific crate.
> release: bump crate versions

- .github/workflows/test.yaml
Using cache used to make sense since cloning the crates.io indexing took very long. This is no longer the case since Rust 1.70.0.
> ci: remove cache for tests

- .github/workflows/test.yaml
These steps interact with live networks and are thus prone to failure.
> ci: retry test workflow steps

- Cargo.lock
- starknet-accounts/Cargo.toml
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-providers/tests/jsonrpc.rs
Starknet v0.12.0 was deployed to testnet and it has caused some tests to failed. This PR changes the following to make tests pass again:
- Forces all transactions sent out to be unique, as the sequencer no longer accepts duplicate transaction submissions;
- Switches to Infura for JSON-RPC, as it seems the sequencer has imposed a stricter rate limit on transaction submission, and using our own node results in failures;
- Updates the event query to be a narrow range as Infura doesn't seem to allow wide range event query.
> test: fix starknet 0.12.0 test failures

- starknet-providers/src/sequencer/mod.rs
2 missing error codes found:
- `INVALID_COMPILED_CLASS_HASH`: this happens when the sequencer disagrees with the CASM hash provided.
- `DUPLICATED_TRANSACTION`: starting from Starknet v0.12.0, the sequencer no longer accepts duplicate transaction submissions and rejects them with this new error code.
> fix(sequencer): missing err codes

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-providers/Cargo.toml
This is technically a breaking change as we're adding new enum variants. However, this only breaks code that's exhausting all options of `ErrorCode`, which is very unlikely.
Therefore, let's just ignore semver and bump `starknet-providers` to `0.4.1` instead :)
> release: bump starknet-providers to 0.4.1

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/mod.rs
- starknet-core/test-data/serde/broadcasted_invoke_v1_non_query.json
- starknet-core/test-data/serde/broadcasted_invoke_v1_query.json
- starknet-providers/tests/jsonrpc.rs
Query tx version support is only applied for `BroadcastXxx` types, as the query version would never exist in a block.
This PR enables applications using `starknet-core` on the server side to accept query version tx requests. However, `starknet-rs` itself does not make use of it yet. This will be addressed in a future version.
> feat: support query tx version

- starknet-providers/src/sequencer/mod.rs
- starknet-providers/test-data/serde/sequencer_error_invalid_contract_class.json
Adds the `INVALID_CONTRACT_CLASS` error code.
> fix(sequencer): missing error code

- Cargo.lock
- starknet-providers/Cargo.toml
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/transports/http.rs
- starknet-providers/src/jsonrpc/transports/mod.rs
- starknet-providers/src/sequencer/mod.rs
Downstream applications often find it difficult to debug provider- related issues since there's currently no way to inspect the traffic. The integration with `log` makes debugging easier.
> feat(providers): provider traffic trace logs

- starknet-accounts/src/factory/mod.rs
- starknet-core/src/types/codegen.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/lib.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
Currently when a matching error code is found, the `message` context is lost in the conversion process. This PR makes the message available again.
This might not be very useful in practice though, due to how JSON-RPC node implementations seem to simply always hard-code the fixed error message derived from the error code itself.
> feat: include error message in provider error

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
This is a breaking release due to incompatible changes in `starknet-core` and `starknet-providers`.
> release: bump starknet to 0.5.0 (and deps)

- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
The network now validates transaction nonces. Using different accounts for different test cases helps reduce the chance of clashing.
> test: use distinct accounts for test cases

- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-providers/Cargo.toml
Just realized that the published crates unnecessarily bundle the `test-data` directory, causing crate sizes to be rather large.
For example, the latest version of `starknet-core` is now 658 kB _compressed_. After this change it will become 29.9 kB instead.
> chore: exclude test data from published crates

- starknet-providers/tests/jsonrpc.rs
Currently each jsonrpc method is only tested once. This PR adds more cases under methods that can return different structures depending on the query.
> test: more jsonrpc test cases

- starknet-core/src/types/mod.rs
Adds methods on enums that return common fields of all variants. This enables users to easily access the fields without resolving into specific variants.
Instead of doing:
```rust
let receipt = provider.xxx();
let hash = match receipt {
MaybePendingTransactionReceipt::Receipt(receipt) => match receipt {
TransactionReceipt::Invoke(receipt) => receipt.transaction_hash,
TransactionReceipt::L1Handler(receipt) => receipt.transaction_hash,
TransactionReceipt::Declare(receipt) => receipt.transaction_hash,
TransactionReceipt::Deploy(receipt) => receipt.transaction_hash,
TransactionReceipt::DeployAccount(receipt) => receipt.transaction_hash,
},
MaybePendingTransactionReceipt::PendingReceipt(receipt) => match receipt {
PendingTransactionReceipt::Invoke(receipt) => receipt.transaction_hash, …
```
> feat: easier tx hash and block tx list access

- starknet-providers/Cargo.toml
When using the `starknet-providers` crate directly, the `no_unknown_fields` feature is incorrectly not propagated into `starknet-core`.
> fix: no_unknown_fields feature not propagated

- Cargo.lock
- examples/declare_cairo0_contract.rs
- examples/declare_cairo1_contract.rs
- examples/deploy_contract.rs
- examples/mint_tokens.rs
- starknet-accounts/Cargo.toml
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/lib.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
Cairo 1 account contracts expect calldata to be formatted differently from Cairo 0 accounts. The library previously assumed that such encoding is universal, which is clearly incorrect. In fact, account contracts should always be free to interpret calldata however they like, regardless of what Cairo version they're written in.
This commit introduces a breaking changes on the `new()` method of `SingleOwnerAccount` on purpose. This commit could have kept the method unchanged and instead uses a default value for `encoding`. However, adding the breaking change helps raise awareness that such difference exists.
> feat: support Cairo 1 account `execute` encoding

- examples/deploy_contract.rs
- starknet-contract/src/factory.rs
Resolves #447.
Changes the return type of `deploy()` from `Execution` to a new type `Deployment`, which exposes a method `deployed_address()` for calculating the target contract address. This new type exposes an API similar to `Execution`, so it's still easy to use.
This is a breaking change but most consuming code shouldn't be affected given the how `Deployment` closely resembles `Execution`.
> feat: compute address for contract deployment

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
New versions:
- `starknet-core`: v0.6.0
- `starknet-signers`: v0.4.0
- `starknet-providers`: v0.6.0
- `starknet-accounts`: v0.5.0
- `starknet-contract`: v0.5.0
- `starknet-macros`: v0.1.3
- `starknet`: v0.6.0
> release: bump starknet to 0.6.0 (and deps)

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/single_owner.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/transaction_request.rs
- starknet-providers/tests/sequencer_goerli.rs
Changes to add `2 ^ 128` to `version` for sending fee estimation requests.
> feat: use query tx version for fee estimation

- examples/parse_jsonrpc_request.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/contract/legacy.rs
There's nothing wrong with `starknet-rs` itself. But some upstream bugs/issues have made some `starknet-rs` stop working:
- https://github.com/eqlabs/pathfinder/issues/1371
- https://github.com/eqlabs/pathfinder/issues/1372
These changes can be reverted once `pathfinder` makes a release with the fixes. However, since this affects downstream applications too, I'm making the changes now.
> fix: work around a few new rpc issues

- examples/deploy_argent_account.rs
- starknet-accounts/src/factory/argent.rs
Argent moved to Cairo 1 accounts.
> feat: change Argent account factory for Cairo 1

- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/open_zeppelin.rs
Thanks to the `block_id` abstraction this has always been possible but not implemented. This PR enables setting the block ID used for nonce fetching and fee estimation when using the two built-in account factory implementations.
> feat: setting block id in account factories

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Making a new non-breaking `starknet-core` release to make the important fix introduced in #478 available on crates.io.
> release: bump starknet-core to 0.6.1

- starknet-core/src/types/codegen.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/requests.rs
- starknet-core/src/types/serde_impls.rs
Regenerates core types from `starknet-jsonrpc-codegen` using the latest version which supports trace methods and schemas.
> feat: generate models for trace methods

- starknet-providers/src/any.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/trace.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
Adds the 3 trace methods to `Provider` with test cases.
> feat: support trace methods in provider

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-contract/src/factory.rs
Adds a `.simulate()` methods to transaction builder types.
> feat: support account transaction simulation

- README.md
- examples/downcast_provider_error.rs
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/mod.rs
- starknet-contract/src/factory.rs
- starknet-providers/src/any.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/lib.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/provider.rs
Changes the `Other` variant of `ProviderError` to use a trait object instead of a generic parameter. This makes the `ProviderError` type much easier to work with, as errors from different `Provider` types are now compatible, and any type that wraps `ProviderError` will have one fewer generic parameter to deal with.
At the same time, it's still possible, though harder, to access the erased error type by downcasting, which requires the caller to know the concrete type at compile time, as showcased in the new example.
This is a breaking change, but it shouldn't affect downstream applications which already erase the whole `ProviderError` type with something like `anyhow`.
> feat: erase implementation-specific provider error

- starknet-crypto/src/ecdsa.rs
Thanks to Michael from @eqlabs for spotting this. This PR changes the `s` upper bound to match the [implementation from `crypto-cpp`](https://github.com/starkware-libs/crypto-cpp/blob/78e3ed8dc7a0901fe6d62f4e99becc6e7936adfd/src/starkware/crypto/ecdsa.cc#L65).
> fix: incorrect upper bound for `s`

- starknet-providers/tests/jsonrpc.rs
Test disabled until https://github.com/eqlabs/pathfinder/pull/1457 is released.
> test: disable reverted invoke trace test

- starknet-crypto/src/ecdsa.rs
Same as #485 but for `sign`, as we need to keep `sign` and `verify` consistent.
> fix: incorrect upper bound for `s` in `sign`

- Cargo.lock
- Cargo.toml
- examples/starknet-wasm/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-signers/Cargo.toml
To make #485 and #486 available.
> release: bump starknet-crypto to 0.6.1

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
It's been a while since the last release. Making this release mainly to make support for trace methods & models available on crates.io.
> release: bump starknet to 0.7.0 (and deps)

- starknet-core/src/types/serde_impls.rs
While the official specs indicate that `NUM_AS_HEX` must be strings, some Starknet libraries expect numbers to be acceptable in certain cases. Adding support for this technically breaks the specs but it's acceptable since it's only on the deserialization side.
Also changes the `NumAsHex` implementation to remove the unnecessary allocation for `String`. This makes deserialization slightly more efficient.
> feat: accept numbers for `NUM_AS_HEX`

- starknet-core/src/serde/byte_array.rs
- starknet-core/src/serde/num_hex.rs
- starknet-core/src/serde/unsigned_field_element.rs
- starknet-core/src/types/eth_address.rs
- starknet-ff/src/lib.rs
Following #491, applies the same visitor-based deserialization to all string-based impls to remove the unnecessary `String` allocation. This should make things very slightly faster and more memory efficient.
> perf: drop useless allocation in deserialization

- starknet-core/src/types/execution_result.rs
The Starknet JSON-RPC spec defines this field as optional. This commit fixes compatibility with nodes like Juno that don't include this field if the revert reason is empty.
> fix: execution status revert reason field is optional

- starknet-core/src/types/mod.rs
- starknet-core/src/types/msg.rs
Resolves #448.
Adds a new type `MsgToL2` that can be manually constructed or parsed from `L1HandlerTransaction`. An infallible function `hash()` is available on the type for calculating message hash.
> feat: new type `MsgToL2` with parsing and hashing

- starknet-core/src/types/hash_256.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/msg.rs
This type will be useful for representing 256-bit hashes like Keccak (non-truncated).
> feat: add `Hash256` type

- starknet-providers/tests/jsonrpc.rs
The `pathfinder` fix has been released with v0.9.4. We no longer need to ignore this test case.
> test: re-enable ignored tests

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Mainly to make #494 available on crates.io.
> release: bump starknet-core to 0.7.2

- starknet-accounts/src/account/mod.rs
This bug causes the default latest block to be used for queries instead of the custom block when the reference type is actually interpreted as `ConnectedAccount`.
> fix: missing method override for ConnectedAccount impls

- README.md
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/requests.rs
- starknet-core/src/types/serde_impls.rs
- starknet-providers/src/any.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/transaction_receipt.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
> feat(jsonrpc): switch to spec 0.5.1

- starknet-accounts/tests/single_owner_account.rs
- starknet-providers/tests/sequencer_goerli.rs
Can no longer run these due to the upgrade to v0.12.3.
> test: ignore sequencer tests for deprecation

- starknet-accounts/src/factory/mod.rs
- starknet-core/src/types/codegen.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/lib.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/mod.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
Greatly simplify provider error code matching. Previously, the error code returned from the RPC is an enum with 2 variants for known and unknown codes to accommodate the fact that JSON-RPC nodes sometimes return codes that are part of the JSON-RPC standard, but are not from the Starknet specifications. This commit changes to move the unknown codes to be handled by the implementation-specific error type instead, making it much easier to match against specification error codes, at the cost of being harder to match the unknown codes.
> feat: revamp provider error handling

- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/mod.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/sequencer/mod.rs
Supersedes #483.
Certain `StarknetError` variants now wrap an inner type, allowing access to the `data` field from JSON-RPC error responses. These variants are:
- `ContractError`
- `UnexpectedError`
- `NoTraceAvailable`
among which `data` for `ContractError` would be the most useful for inspecting error details.
> feat: parse data field for provider errors

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Making this release such that at least we have a crate version that works with JSON-RPC v0.5.1 on crates.io, for those who need to use dependencies from crates.io only.
> release: bump starknet to 0.8.0 (and deps)

- starknet-providers/src/lib.rs
This type is needed to initialize a JSON-RPC client. Having this type re-exported makes it eaiser to use, as applications would not have to import the `url` crate themselves nor worry about the version.
> feat: re-export `Url` in `starknet-providers`

- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/mod.rs
- starknet-providers/src/sequencer/models/transaction_request.rs
This type has been made useless by #516. Forgot to remove it in that PR.
> refactor: remove unused `AccountTransaction` type

- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/mod.rs
- starknet-providers/src/sequencer/models/serde_impls.rs
- starknet-providers/src/sequencer/models/transaction.rs
- starknet-providers/src/sequencer/models/transaction_receipt.rs
- starknet-providers/src/sequencer/models/transaction_request.rs
Adds support for sending v3 transaction requests to the sequencer gateway.
> feat(sequencer): v3 transaction request

- starknet-providers/tests/jsonrpc.rs
Juno v0.8.1 now correctly serves `0.6.0`.
> test: undo ignoring spec_version test

- starknet-ff/src/lib.rs
> refactor: use `deserialize_str` instead

- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-providers/tests/jsonrpc.rs
Pathfinder v0.10.2 fixed all previously known issues regarding JSON-RPC v0.6.0.
Switches back to Pathfinder for running the integration tests as testing against Juno is flaky.
> test: switch to pathfinder for integration tests

- starknet-core/src/types/mod.rs
In the Starknet Spec, the `continuation_token` is not a required field. So in the last event page, the `continuation_token` must be absent from the response instead of being null. I also tried this with the infura RPC (which uses pathfinder?) and works in the same way. We are integrating Madara with the explorer and that's breaking because of this.
> fix: skip serialization of continuation token if `None`

- starknet-core/src/types/contract/legacy.rs
Fixes #533.
Some legacy contract classes are missing this field. Thankfully, this patch does not affect class hash calculation, as `accessible_scopes` is skipped when empty in the first place.
> fix: failed deserialization when `accessible_scopes` is missing

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
Certain custom `Account` implementations require access to these internal fields, as they do more than just signing on the transaction hash. Exposing these fields offers the maximum flexibility on how accounts sign transactions.
Not exposing these fields results in exotic implementations like [this one](https://github.com/neotheprogramist/cairo-webauthn/pull/21/files#r1440597653). So it's really not good.
Adding getters instead of just making the fields `pub` though, to still retain a certain degree of encapsulation.
> feat: private field access for `RawXxx` types

- Cargo.lock
- Cargo.toml
- README.md
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
To make JSON-RPC v0.6.0 support available on crates.io.
> release: bump starknet to 0.9.0 (and deps)

- README.md
- examples/declare_cairo0_contract.rs
- examples/declare_cairo1_contract.rs
- examples/deploy_argent_account.rs
- examples/deploy_contract.rs
- examples/erc20_balance.rs
- examples/get_block.rs
- examples/jsonrpc.rs
- examples/mint_tokens.rs
The current examples use the sequencer gateway, which has already been deprecated, and does not work in most cases.
> [!NOTE]
>
> It technically still works in the `get_block` example. But it's better to teach a new user to use JSON-RPC for that.
The PR also updates the account encoding from `Legacy` to `New`, considering that new users now most likely have Cairo 1 accounts.
> chore: update examples to use jsonrpc and cairo 1 accounts

- starknet-curve/src/ec_point.rs
At the moment, when using `add_assign` for `ProjectivePoint`, the case P + (-P) was not taken into account, leading to 2P instead of infinity point. 
For this purpose a piece of logic is added to check, during P1 + P2 addition and in the case where x1 = x2, if y1 = y2 (should return point doubling) or if y1 = -y2 (should return infinity point).
Also some of the logic on other implementations of `add_assign` is simplified to remove some useless code.
> fix `add_assign` for `ProjectivePoint`

- starknet-curve/src/ec_point.rs
At the moment, to construct a projective point from an affine point, the `from_affine_point` always consider `infinity` as false. 
However, this will be wrong if the affine point is the identity point, for which `infinity` has to be `true`. 
For this purpose, the `from_affine_point` method is modified to always take into account the `infinity` attribute from the provided `p` affine point during the construction of the projective point.
> Fix `from_affine_point` infinity definition

- Cargo.lock
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
To make #542 and #543 available on [crates.io](https://crates.io/).
> release: bump starknet-curve to 0.4.1

- starknet-accounts/tests/single_owner_account.rs
- starknet-crypto-codegen/src/poseidon/mod.rs
- starknet-crypto/src/poseidon_hash.rs
- starknet-curve/src/ec_point.rs
- starknet-ff/src/lib.rs
This pull request proposes a performance enhancement in the implementation of elliptic curve operations. Instead of using a full multiplication operation like `FieldElement::TWO * a` to handle doubling (2 * a), it suggests utilizing the `double` method available in the `FieldElement` struct. 
The rationale behind this enhancement is that the doubling operation (a + a) requires only one addition between field elements, which is more performant compared to a full multiplication. Therefore, replacing multiplication with addition can improve the efficiency of various computations involving point doubling in elliptic curve arithmetic.
- Added logic to utilize the `double` method from the `FieldElement` struct for doubling operations.
- Updated relevant computations to use the `double` method …
> feat: `double` method for `FieldElement`

- Cargo.lock
- starknet-accounts/Cargo.toml
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-providers/tests/jsonrpc.rs
The goerli network will be taken down soon. Moves all JSON-RPC test cases to sepolia. Tests that are not applicable to sepolia (e.g. `DEPLOY` v0 transactions) are removed.
> test: move jsonrpc tests to sepolia

- starknet-core/src/chain_id.rs
Add the `sepolia` chain ID to the `chain_id` module.
> feat: Add `sepolia` to the `chan_id` module

- .github/workflows/lint.yaml
- starknet-core/src/serde/byte_array.rs
- starknet-core/src/types/codegen.rs
- starknet-core/src/types/contract/legacy.rs
- starknet-core/src/types/contract/mod.rs
- starknet-core/src/types/execution_result.rs
- starknet-core/src/types/mod.rs
- starknet-core/src/types/msg.rs
- starknet-core/src/utils.rs
Related: https://doc.rust-lang.org/std/prelude/
> fix nightly imports

- starknet-core/src/types/mod.rs
- The `parse_msg_to_l2` method is simplified using `split_first` for `calldata` in order to decouple easily the `from_address` and the `payload`, handling potential errors in the mean time.
- Unit tests are added to tackle `ParseMsgToL2Error::EmptyCalldata` and `ParseMsgToL2Error::FromAddressOutOfRange` possible scenarios.
> Simplify `parse_msg_to_l2` method and add unit tests

- starknet-curve/src/ec_point.rs
During the multiplication of a projective point by a scalar, the leading zeros can be skipped in the loop, because they induce unnecessary doubling calculations, giving always the identity value back before the first non zero element is reached in the `rhs` boolean array.
Skipping this useless calculations can reduce drastically the calculation costs, especially for small numbers (for example, is our scalar is 1, then 255 useless doubling are performed).
> Improve projective mul by scalar perf

- starknet-crypto/src/pedersen_hash.rs
This pull request enhances the Pedersen hash implementation by making the following improvements:
- Replaced the `bools_to_usize_le` function with a more efficient iteration over the slice of bool `v`, eliminating unnecessary overhead (no change in perf detected through benchmark).
- Added an additional test case configuration for the Pedersen hash.
> Refactor Pedersen hash and add test case

- Cargo.lock
- Cargo.toml
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-ff/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Bumping `starknet` to v0.10.0, mainly to release the Sierra 1.5.0 support added in #565. Unfortunately, that PR introduced minor breaking changes:
- a new `bytecode_segment_lengths` field was added to `CompiledClass`
- a few new enum variants were added to `ComputeClassHashError`
While these are minor breakge and it's deemed very unlikely that anyone would actually get broken, as more and more applications depend on `starknet-rs`, it's more reasonable to fully adhere to SemVer and to bump version to `0.10.0` instead of `0.9.1`.
> release: bump starknet to 0.10.0 (and deps)

- .github/workflows/lint.yaml
- starknet-contract/tests/contract_deployment.rs
- starknet-crypto/src/test_utils.rs
A new nightly lint `non_local_definitions` is failing CI.
> ci: allow some nightly lints

- Cargo.lock
- examples/declare_cairo1_contract.rs
- examples/deploy_argent_account.rs
- examples/deploy_contract.rs
- examples/mint_tokens.rs
- starknet-accounts/Cargo.toml
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/src/factory/open_zeppelin.rs
- starknet-accounts/src/lib.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/src/factory.rs
- starknet-contract/tests/contract_deployment.rs
Adds support for v3 transactions on account types. Methods like `.execute()` are replaced with suffixed versions like `.execute_v1()` and `.execute_v3()`. The original `.execute()` methods are still kept for now, but deprecated. To minimize breakage, these deprecated methods point to pre-v3 transactions instead of the latest, recommended v3 transactions.
> feat: support v3 transactions

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-core/src/types/mod.rs
Similar to setting gas limit on Ethereum txs, setting L1 gas on a v3 Starknet tx signals that the caller understands the tx's impact. Previously, the library would incorrectly always perform a full fee estimation as long as any of `gas` and `gas_price` is not specified.
> feat: do not estimate fee when gas is specified

- starknet-accounts/src/factory/mod.rs
No way to set `nonce` on `AccountDeploymentV3`.
> fix: missing nonce setter for `AccountDeploymentV3`

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
When using JSON-RPC v0.7.0, the fee estimate returned contains data gas info. Naively using `gas_consumed` as max gas amount results in insufficient fees. The correct way to do it is to calculate a pseudo gas amount by dividing the overall fee by the gas price.
> fix: incorrect v3 max gas amount calculation

- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/codegen.rs
Also updates to use a higher L1 gas amount for tests to avoid failures as Sepolia gas prices fluctuate a lot.
> fix: remove unknown cfg conditions

- starknet-providers/src/sequencer/mod.rs
This PR add the error code `StarknetErrorCode.VALIDATE_FAILURE` from sequencer API.
> feat: sequencer error code `VALIDATE_FAILURE`

- .github/workflows/build.yml
- examples/starknet-cxx/CMakeLists.txt
- examples/starknet-cxx/starknet-cxx/CMakeLists.txt
Fixes a recent breaking change in corrosion-rs breaking the starknet-cxx example. Also adds a CI workflow for checking the integration example.
> fix: corrosion cpp integration

- src/lib.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-providers/tests/jsonrpc.rs
Resolves new nightly lints.
Also disables the Cairo 0 declaration test as it looks like it's now blocked on Sepolia.
> chore: make nightly clippy happy

- starknet-core/src/types/eth_address.rs
- starknet-core/src/types/hash_256.rs
So that these types can be constructed in a `const` context.
> feat: const ctors for `EthAddress` and `Hash256`

- starknet-core/src/types/mod.rs
Adding these checks to make sure the upcoming change of Felt type from #562 won't break existing `to_string` impls.
> test: felt type to_string tests

- Cargo.lock
- Cargo.toml
- README.md
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto-codegen/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Main changes for this release:
- JSON-RPC 0.7.1 support
- v3 transaction support
- migration to `Felt` type from `starknet-types-core`
> release: bump starknet to 0.11.0 (and deps) (#576)

- starknet-core/src/crypto.rs
- starknet-crypto/src/poseidon_hash.rs
closes #575
No breaking change as both new impl are backward compatible with the only previously allowed input type `&[FieldElement]`
> feat: make hasher accept iterators rather than arrays

- starknet-core/src/types/contract/legacy.rs
https://github.com/eqlabs/pathfinder/issues/1371 has been fixed, no reason to keep the workaround here
> feat: compress `LegacyProgram.debug_info` field as `None`

- Cargo.lock
- Cargo.toml
- README.md
- examples/deploy_account_with_ledger.rs
- examples/ledger_public_key.rs
- starknet-signers/Cargo.toml
- starknet-signers/src/ledger.rs
- starknet-signers/src/lib.rs
The very first attempt at adding Ledger support. The Ledger support is feature-gated by a `ledger` feature on both the `starknet-signers` and `starknet` crates. It's turned off by default.
The current Ledger app for Starknet is quite limited: it only supports blind signing. Nevertheless, it's a huge step forward compared to software keystores.
This PR adds 2 examples that work as long as you have Ledger plugged in, unlocked, and the Starknet app open. Test with:
```console
cargo run --example ledger_public_key
cargo run --example deploy_account_with_ledger
```
Major caveats of the current implementation:
1. Confirming the public key on the device's screen is not supported;
2. Higher-level types like `Account` and `AccountFactory` still hold the assumption that all signers are …
> feat: ledger signer support

- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/src/factory/open_zeppelin.rs
Prevents replay attack and more importantly setting the stage for adding distinction between interactive and non-interactive signers, a necessary feature for practical use of hardware wallets.
This is a breaking change as the `AccountFactory` trait API has changed.
> feat: use query txs for account deployment simulation

- starknet-core/Cargo.toml
Before the migration to the new felt type, we used to be able to do `felt.try_into<u128>()` but the implementation has been removed since. The `num-traits` feature pretty much add implementations for the conversion to primitive uint types.
Would be nice to have it enabled directly from `starknet-rs` instead of having to add the `starknet-types-core` crate manually.
> Enable `num-traits` feature in `starknet-types-core`

- .github/workflows/test.yaml
GitHub removed hosted `macos-11` runners.
> ci: replace macos-11 with macos-12

- README.md
- examples/declare_cairo1_contract.rs
- examples/deploy_account_with_ledger.rs
- examples/deploy_argent_account.rs
- examples/mint_tokens.rs
- examples/transfer_with_ledger.rs
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/src/factory/open_zeppelin.rs
- starknet-accounts/src/single_owner.rs
- starknet-signers/src/ledger.rs
- starknet-signers/src/local_wallet.rs
- starknet-signers/src/signer.rs
Makes signer implementations specify whether a signing operation is "interactive" (or just expensive). Utilizing this new information, `Account` and `AccountFactory` now make more informed decisions on whether to request real signatures for different types of operations.
The most significant benefit of this change is allowing using hardware wallet without excessive unnecessary signing requests.
This PR is made a breaking change, despite the possibility of maintaining backward compatibility by providing default implementations of the new trait methods. This is because #611 has already introduced a breaking change on `starknet-signers` anyway.
Breaking changes include:
- `get_invoke_request` and `get_declare_request` methods are no longer `pub`; it was a mistake making them public in the …
> feat: signer interactivity

- Cargo.lock
- starknet-crypto/Cargo.toml
Should be enabled when `std` is used on `starknet-crypto`.
> fix: `std` not enabled for `starknet-types-core`

- starknet-signers/src/ledger.rs
Separating `LedgerSigner` and `LedgerStarknetApp` to allow usage outside of the `Signer` trait context.
> feat: add `LedgerStarknetApp` type for Ledger specific operations

- Cargo.lock
- starknet-signers/Cargo.toml
- starknet-signers/src/ledger.rs
Add support for the `GetVersion` command of the Ledger app. With this addition all current functionalities of the Ledger app are supported in `starknet-rs`.
> feat: get ledger app version

- starknet-core/src/types/mod.rs
To allow importing error types (eg `FromStrError`) from the `felt` module of `starknet-types-core` directly.
We could just re-export the error types only, but i don't see any harm in re-exporting the entire module.
> starknet-core: re-export entire `felt` module from `starknet-types-core`

- README.md
A link from cairo-contracts repo can be provided as branch release v0.6.1.
> docs(README): link version IAccount.cairo

- starknet-crypto/Cargo.toml
- starknet-crypto/src/pedersen_hash.rs
Closes https://github.com/xJonathanLEI/starknet-rs/issues/609 
Removes current Pedersen implementation & replaces with the one implemented in `type-rs`
cc @tcoratger @xJonathanLEI please review and check if this is what the #609 meant (that's our understanding).
> feat: replace Pedersen implementation with type-rs

- starknet-accounts/src/account/mod.rs
The warning message suggests a method that doesn't exist.
> Replace declare_v1 suggestion with declare_v2

- Cargo.lock
- starknet-core/Cargo.toml
- starknet-core/src/serde/num_hex.rs
- starknet-core/src/serde/unsigned_field_element.rs
- starknet-core/src/types/hash_256.rs
This PR improves the serde impls used to mainly de/serialize the `FieldElement` type. The de/serialization implementations now take into consideration whether `Serialize`/`Deserialize` implementations should expect to de/serialize in human-readable form or not.
This possibly(?) introduces a breaking change due to this PR #527.
> feat: de/serialize based on human readability

- starknet-crypto/src/lib.rs
- starknet-crypto/src/poseidon_hash.rs
Closes #608 
Removes current Poseidon implementation & replaces with the one implemented in type-rs
> feat: replace poseidon impl with type-rs

- starknet-curve/README.md
- starknet-curve/src/curve_params.rs
- starknet-curve/src/lib.rs
> docs: add docs for `starknet-curve`

- .github/workflows/doc.yml
- examples/starknet-cxx/starknet-cxx/src/lib.rs
- starknet-core/src/serde/mod.rs
- starknet-core/src/types/eth_address.rs
- starknet-core/src/types/hash_256.rs
- starknet-core/src/types/receipt_block.rs
- starknet-core/src/utils.rs
- starknet-providers/src/jsonrpc/transports/http.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/mod.rs
Fixes a few broken links and adds a new CI check for ensuring `cargo doc` succeeds without warnings.
> docs: fix broken links and add CI

- starknet-signers/src/key_pair.rs
- starknet-signers/src/ledger.rs
- starknet-signers/src/lib.rs
- starknet-signers/src/local_wallet.rs
- starknet-signers/src/signer.rs
> docs: add docs for `starknet-signers`

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/call.rs
- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/src/factory/open_zeppelin.rs
- starknet-accounts/src/lib.rs
- starknet-accounts/src/single_owner.rs
> docs: add docs for `starknet-accounts`

- starknet-contract/src/factory.rs
- starknet-contract/src/lib.rs
> docs: add docs for `starknet-contract`

- src/lib.rs
- starknet-macros/src/lib.rs
> docs: add docs for `starknet-macros`

- Cargo.lock
- starknet-signers/Cargo.toml
A new version `0.12.0` has been released with the necessary patch: https://github.com/summa-tx/coins/pull/138.
> chore: use `coins-ledger` from crates.io

- starknet-core/src/types/contract/legacy.rs
- starknet-core/src/types/contract/mod.rs
Adds test cases that asserts contract artifacts are not corrupted whether deserialized directly or via the `ContractArtifact` enum. The test for `LegacyContractClass` - `test_legacy_artifact_deser_from_contract_artifact` - is ignored due to a known issue #392.
> test: contract artifact deserliazation integrity

- examples/mint_tokens.rs
- examples/transfer_with_ledger.rs
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/argent.rs
- starknet-accounts/src/factory/open_zeppelin.rs
- starknet-accounts/src/lib.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/src/factory.rs
- starknet-core/src/types/call.rs
- starknet-core/src/types/mod.rs
- starknet-signers/src/ledger.rs
- starknet-signers/src/lib.rs
- starknet-signers/src/local_wallet.rs
- starknet-signers/src/signer.rs
Signer interactivity seems to also be non-binary. This PR enables signer implementations to make better interactivity reporting decision based on what's being signed.
A use case for this would be that calls to a specific contract on certain selectors might be deemed safe and would not require user confirmation. Apparently this needs to be enforced on the actual account contract, but having accurate interactivity on the client side helps the library make better decision on transaction estimation and simulation.
This is technically a breaking change on the existing `HEAD` but since this whole interactivity feature hasn't been released yet so we're free to break anything.
> feat: dynamic signer interactivity

- .github/workflows/lint.yaml
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
- starknet-core/src/types/eth_address.rs
- starknet-core/src/types/mod.rs
> chore: make clippy happy again

- README.md
- examples/batch.rs
- examples/parse_jsonrpc_request.rs
- starknet-providers/src/any.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/transports/http.rs
- starknet-providers/src/jsonrpc/transports/mod.rs
- starknet-providers/src/lib.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
Resolves #593. Supersedes #600.
Implements a type-safe version of the JSON-RPC batch request feature. Users can now do this:
```rust
let responses = provider
.batch_requests([
ProviderRequestData::BlockNumber(BlockNumberRequest),
ProviderRequestData::GetBlockTransactionCount(GetBlockTransactionCountRequest {
block_id: BlockId::Number(100),
}),
])
.await
.unwrap();
match (&responses[0], &responses[1]) {
(
ProviderResponseData::BlockNumber(block_number),
ProviderResponseData::GetBlockTransactionCount(count),
) => {
println!("The latest block is #{}", block_number);
println!("Block #100 has {} transactions", count);
}
_ => panic!("unexpected response type"),
}
```
and the underlying requests would be sent in the just one HTTP request.
> feat: jsonrpc batch requests

- starknet-crypto/src/lib.rs
- starknet-crypto/src/poseidon_hash.rs
This function is no longer really needed but removing a public function is a SemVer breaking change. The breakage is totally unnecessary here.
> chore: add `poseidon_permute_comp` back

- .github/workflows/lint.yaml
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
Allows `clippy::needless_return` as it causes false positives in tests.
> chore: make nightly clippy happy again

- scripts/run_bench_wasm.sh
`./scripts/run_bench_wasm.sh wasmtime` no longer works due to https://github.com/bytecodealliance/wasmtime/issues/7384. Updates the command for `wasmtime` to use the new format.
> chore: adapt wasmtime 14 CLI parsing changes

- .github/workflows/test.yaml
`macos-14` uses M1 according to [the docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
> ci: run tests on Apple silicon runners

- Cargo.lock
- Cargo.toml
- README.md
- assets/CORE_DERIVE_README.md
- examples/serde.rs
- starknet-core-derive/Cargo.toml
- starknet-core-derive/README.md
- starknet-core-derive/src/lib.rs
- starknet-core/Cargo.toml
- starknet-core/src/codec.rs
- starknet-core/src/lib.rs
Adds initial support for serialization of Rust types into `Felt`s as well as deserialization.
This PR adds two new traits as `starknet_core::codec::Encode` and `starknet_core::codec::Decode`. Common Rust primitive types such as `u64` and `Option<T>` implement these traits, following the same rules as the `Serde` trait in Cairo.
These two traits are derivable. Users can simple write something like:
```rust
#[derive(Encode, Decode)]
struct CairoType {
a: Felt,
b: Option<u32>,
c: bool,
}
```
A new example `serde` has been added to demonstrate the usage of these new building blocks.
This is useful for constructing contract calldata and interpreting contract call responses fetched from JSON-RPC. Previously, users would have to manually decode the raw `Felt`s into proper Rust types.
For now, …
> feat: serialization to and from felts

- examples/serde.rs
- starknet-core/src/codec.rs
Makes `Vec<T>` and arrays implement `Encode` and `Decode`.
> feat: implement `Encode` and `Decode` for primitive collection types

- starknet-core/src/codec.rs
Adds unit-tested code examples to both traits.
> docs: better docs for `Encode` and `Decode`

- .github/workflows/test.yaml
- starknet-crypto/Cargo.toml
- starknet-crypto/README.md
- starknet-crypto/src/pedersen_hash/default.rs
- starknet-crypto/src/pedersen_hash/mod.rs
- starknet-crypto/src/pedersen_hash/no_lookup.rs
Adds a new `pedersen_no_lookup` feature on `starknet-crypto` that changes the Pedersen hash implementation to an unoptimized one that's around 10x as slow. In exchange, the produced binary size would be smaller. This can be very useful in cases where binary size is very important (e.g. browser), whereas Pedersen hash is minimally used.
This feature is not exposed through higher-level crates to avoid misuse, as enabling it imposes a heavy penalty on performance.
> feat: alternative (slow) pedersen hash impl optimized for size

- Cargo.lock
- Cargo.toml
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-signers/Cargo.toml
Makes #675 available. This release is non-breaking.
> release: bump starknet-crypto to 0.7.3

- examples/starknet-wasm/src/lib.rs
- starknet-core/src/types/mod.rs
Adds a `.events()` helper function on `TransactionReceipt` to allow easy access to the underlying events without explicit matching.
> feat: `.events()` helper on `TransactionReceipt`

- examples/deploy_argent_account.rs
- starknet-accounts/src/factory/argent.rs
Resolves #626. Contains an API breaking change on the signature of `ArgentAccountFactory::new()`.
Technically this can be implemented without a breaking change by simply treating a guardian public key of `Felt::ZERO` as `None` internally. However, the change in constructor param serialization itself is a breaking change. In order to explicitly signal the breakage the `new()` signature is changed too to avoid silently breaking downstream.
> feat: support Argent account v0.4.0

- starknet-core/src/types/byte_array.rs
- starknet-core/src/types/mod.rs
> feat: `ByteArray` type

- starknet-crypto/src/lib.rs
- starknet-crypto/src/pedersen_hash/mod.rs
Similar to `PoseidonHasher`, the new `PedersenHasher` type is a stateful hasher that does the same thing as `starknet_core::crypto::compute_hash_on_elements`.
> feat: pedersen hasher type

- starknet-core/src/codec.rs
Implements `Encode` and `Decode` for `i128`. Previously only unsigned integers can be encoded/decoded.
> feat: codec traits impl for `i128`

- starknet-contract/tests/contract_deployment.rs
The current version of the library is meant to work with JSON-RPC v0.7.x.
> test: fix incorrect test urls with `v0_6`

- examples/declare_cairo1_contract.rs
- examples/deploy_account_with_ledger.rs
- examples/deploy_argent_account.rs
- examples/deploy_contract.rs
- examples/mint_tokens.rs
- examples/transfer_with_ledger.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/src/factory.rs
- starknet-contract/tests/contract_deployment.rs
Pre-v3 transactions are now deprecated and will be disabled on Starknet soon. This PR deprecates all non-v3 methods to add a compilation warnings to downstream applications.
> feat: deprecate pre-v3 transactions

- Cargo.lock
- Cargo.toml
- README.md
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Makes a bunch of new features available, mainly:
- deprecation of pre-v3 transactions;
- initial `TypedData` (SNIP-12) support;
- native `ByteArray` type;
among other minor improvements.
> release: bump starknet to 0.13.0 (and deps)

- starknet-accounts/src/factory/mod.rs
in `PreparedAccountDeploymentV3::transaction_hash()` resource buffer for l1_data_gas property is incorrectly filled 2 times with l1_data_gas
> Fix runtime error during transaction hash calculation

- starknet-core/src/types/typed_data/mod.rs
- starknet-core/src/types/typed_data/types.rs
`starknet-rs` currently ships a rather correct implementation of [SNIP-12](https://github.com/starknet-io/SNIPs/blob/be4423ab0a6bf0678e8d5a66c712dd160b47334c/SNIPS/snip-12.md). Unfortunately, the de-facto standard `starknet.js` ships multiple bugs: https://github.com/starknet-io/starknet.js/pull/1292.
Despite all 3 fixes being merged, only the enum dependency fix (https://github.com/starknet-io/starknet.js/pull/1289) is currently expected to ever be released. Therefore, this "alignment" PR uses message hashes generated from `starknet.js` [v6.24.0](https://github.com/starknet-io/starknet.js/releases/tag/v6.24.0) _plus a patch of https://github.com/starknet-io/starknet.js/pull/1289_.
> [!NOTE]
>
> The test case `test_message_hash_v1_with_simple_enum` is indifferent to whether the patch is …
> feat: port starknet.js SNIP-12 deviations

- starknet-core/src/types/typed_data/mod.rs
Starknet.js released [v6.24.1](https://github.com/starknet-io/starknet.js/releases/tag/v6.24.1) containing the fix for enum type encoding with custom dependency types. It's no longer necessary to use a patched v6.24.0 for test data generation. The existing comments could be misleading.
> docs: update notes on starknet.js SNIP-12 test data

- .github/workflows/lint.yaml
- README.md
- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-core/src/types/codegen.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
Specs 0.8.1 changed some fields to be concrete primitive types instead of `Felt`. This is a breaking change and will be released alongside other long-overdue breakages.
> feat: update to jsonrpc v0.8.1

- starknet-core/src/types/codegen.rs
- starknet-core/src/types/mod.rs
Avoids duplication of field definitions between `AsObject` and `FieldX`. Makes code easier to maintain.
> refactor: simplify jsonrpc request type parsing

- starknet-core/src/types/codegen.rs
Currently requests are serialized as arrays, which do not work with multiple optional fields.
> feat: serialize jsonrpc request params as objects

- starknet-core/src/types/codegen.rs
- starknet-core/src/types/mod.rs
- starknet-providers/src/jsonrpc/mod.rs
Certain fields in the `starknet_getStorageProof` should have been optional according to the specs. The library has been treating them as mandatory as using an empty `Vec` should be equivalent to omitting a field, at least on the client side.
However, this wouldn't work when using the library on the server side, or in future cases where the default value of a field is different from its omission.
This PR utilizes the new optional field support from `starknet-jsonrpc-codegen` to turn these fields into `Option<>`.
This is a breaking change.
> feat: optional jsonrpc request fields

- Cargo.lock
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
Uses the latest breaking release of `reqwest`.
> chore: bump reqwest to 0.12

- examples/declare_cairo1_contract.rs
- examples/deploy_contract.rs
- examples/mint_tokens.rs
- examples/transfer_with_ledger.rs
- starknet-accounts/src/single_owner.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/tests/contract_deployment.rs
Many new users of the library ran into nonce conflict issues that can be traced back to using the latest block for accounts. Changing the default block to pending helps reduce the friction.
This is a breaking change but the next release will be bundled with a couple of other breaking changes.
> feat: change default account block to pending

- starknet-core/src/types/codegen.rs
The current `Display` impl for `StarknetError` generated by `starknet-jsonrpc-codegen` only emits the error variant name and not its content, forcing downstream applications to manually map errors if they want those printed.
This PR uses a newer generator version that surfaces the inner errors in debug format.
> feat: print error data for `StarknetError` Display impl

- Cargo.lock
- Cargo.toml
- README.md
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
- starknet-tokio-tungstenite/Cargo.toml
Publishes some breaking changes needed for the WebSocket implementation added in #725, along with some other long overdue breakage such as bumping `reqwest`.
> release: bump starknet to 0.15.0 (and deps)

- Cargo.lock
- Cargo.toml
- starknet-providers/Cargo.toml
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/jsonrpc/transports/mod.rs
- starknet-providers/src/jsonrpc/transports/worker.rs
Adds a new feature-gated `WorkersTransport` type for using the library to connect to Starknet JSON-RPC nodes in a Cloudflare Workers environment.
The feature can be enabled either via the `worker` feature on `starknet` crate or the `worker` feature on the `starknet-providers` crate.
> feat: cloudflare workers jsonrpc transport

- .github/workflows/lint.yaml
- starknet-core/src/types/typed_data/encoder.rs
- starknet-core/src/types/typed_data/mod.rs
- starknet-core/src/types/typed_data/type_definition.rs
- starknet-core/src/types/typed_data/type_reference.rs
Supersedes #724.
The SNIP-12 API has been rather limited since support was first added. This PR opens up the encoding side things, allowing access to an `Encoder` type that offers an API to allow encoding any custom types defined.
The approach here differs from the one proposed by #724 as in it makes no assumption on what components downstream libs/apps might want. They would just cherry-pick the parts and call directly.
> feat: expose snip-12 encoding api

- starknet-signers/tests/ledger.rs
Makes use of Speculos's button automation feature to run Ledger integration tests that involve using the device interactively. This unlocks more complex test cases like approving and sending transactions.
> test: ledger integration test with button automation

- .github/workflows/test.yaml
- Cargo.lock
- starknet-signers/Cargo.toml
- starknet-signers/tests/ledger.rs
Cleaned up and refactored the Speculos client implementation into a new crate [`speculos-client`](https://crates.io/crates/speculos-client) as it needs to be reused in `starknet-accounts` tests as well.
> chore: use `speculos-client` for ledger tests

- Cargo.lock
- Cargo.toml
- starknet-tokio-tungstenite/Cargo.toml
> release: bump starknet-tokio-tungstenite to 0.1.2

- starknet-core/src/types/mod.rs
- starknet-core/src/types/receipt_block.rs
- starknet-providers/src/any.rs
- starknet-providers/src/jsonrpc/mod.rs
- starknet-providers/src/provider.rs
- starknet-providers/src/sequencer/models/conversions.rs
- starknet-providers/src/sequencer/models/transaction_receipt.rs
- starknet-providers/src/sequencer/provider.rs
- starknet-providers/tests/jsonrpc.rs
- Change `MaybePending*` to `MaybePreConfirmed*`
- Leave sequencer models as-is.
- Address occurrences of "pending" in receipt_block.rs.
- Address occurrences of "pending" in code docs.
- Fix a few typos in code docs ("teh", "toggether").
> Address remaining occurrences of "pending"

- starknet-tokio-tungstenite/Cargo.toml
- starknet-tokio-tungstenite/tests/websocket.rs
Adds WebSocket integration testing. Tests passing against a modified `pathfinder` with a patch for https://github.com/eqlabs/pathfinder/issues/2859.
> test: websocket integration tests

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/account/mod.rs
- starknet-accounts/src/factory/mod.rs
- starknet-accounts/tests/single_owner_account.rs
- starknet-contract/src/factory.rs
- starknet-core/src/types/mod.rs
This change adds very basic support to set a non-zero tip on transactions sent.
> feat: add transaction tip support

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
The tip field has been added to `RawExecutionV3` and `RawDeclarationV3` but the `tip()` getter method was missing.
> fix: add missing `tip` getters to raw execution types

- examples/deploy_contract.rs
- starknet-contract/src/factory.rs
- starknet-contract/src/lib.rs
- starknet-contract/tests/contract_deployment.rs
Deprecates the old `new()` constructor in favour of the more specific `new_with_udc()`.
> feat: built-in support for new UDC

- starknet-accounts/src/account/declaration.rs
- starknet-accounts/src/account/execution.rs
- starknet-accounts/src/factory/mod.rs
Currently, there doesn't seem to be a way to get the raw broadcasted tx request.
> feat: make getting broadcasted tx request methods public

- Cargo.lock
- Cargo.toml
- examples/starknet-wasm/Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-core/Cargo.toml
- starknet-crypto/Cargo.toml
- starknet-curve/Cargo.toml
- starknet-signers/Cargo.toml
While most crates in the repo are still in RC stage, these 2 low-level crates should be released directly to expose #774 for the rest of the ecosystem to integrate.
> release: breaking releases for `starknet-curve` and `starknet-crypto`

- Cargo.lock
- Cargo.toml
- starknet-accounts/Cargo.toml
- starknet-contract/Cargo.toml
- starknet-core/Cargo.toml
- starknet-macros/Cargo.toml
- starknet-providers/Cargo.toml
- starknet-signers/Cargo.toml
- starknet-tokio-tungstenite/Cargo.toml
Note that this RC uses new breaking versions of `starknet-curve` and `starknet-crypto` due to the breaking version change of the underlying `starknet-types-core`.
> release: bump starknet to 0.17.0-rc.4 (and deps)
